#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/../.." && pwd)"
SPRING_DIR="$REPO_ROOT/spring"
FIXTURE="$SPRING_DIR/src/test/resources/db/rails/rails_schema.sql"
MIGRATION="$SPRING_DIR/src/main/resources/db/migration/V1__baseline_rails_schema.sql"
CHECK_MODE=false

if [[ "${1:-}" == "--check" ]]; then
    CHECK_MODE=true
elif [[ "$#" -gt 0 ]]; then
    printf 'Usage: %s [--check]\n' "$0" >&2
    exit 2
fi

mapfile -t SCHEMA_VERSIONS < <(
    sed -nE \
        's/^[[:space:]]*ActiveRecord::Schema\[[^]]+\]\.define\(version:[[:space:]]*([0-9_]+)\).*$/\1/p' \
        "$REPO_ROOT/db/schema.rb"
)
if [[ "${#SCHEMA_VERSIONS[@]}" -ne 1 ]]; then
    printf 'Expected one ActiveRecord::Schema version declaration in db/schema.rb; found %s.\n' \
        "${#SCHEMA_VERSIONS[@]}" >&2
    exit 1
fi
SCHEMA_VERSION="${SCHEMA_VERSIONS[0]}"

TEMP_DIR="$(mktemp -d)"
CONTAINER_ID=""
CREATED_DATABASE_YML=false

cleanup() {
    if [[ -n "$CONTAINER_ID" ]]; then
        docker rm -f "$CONTAINER_ID" >/dev/null 2>&1 || true
    fi
    if [[ "$CREATED_DATABASE_YML" == true ]]; then
        rm -f "$REPO_ROOT/config/database.yml"
    fi
    rm -rf "$TEMP_DIR"
}
trap cleanup EXIT

if [[ ! -f "$REPO_ROOT/config/database.yml" ]]; then
    cp "$REPO_ROOT/config/database.postgres.yml" "$REPO_ROOT/config/database.yml"
    CREATED_DATABASE_YML=true
fi

CONTAINER_ID="$(docker run -d \
    -e POSTGRES_PASSWORD=postgres \
    -p 127.0.0.1::5432 \
    "${PG_IMAGE:-postgres:16}")"
PORT="$(docker port "$CONTAINER_ID" 5432/tcp | sed 's/.*://')"

for attempt in $(seq 1 60); do
    if docker exec "$CONTAINER_ID" pg_isready -U postgres >/dev/null 2>&1; then
        break
    fi
    if [[ "$attempt" -eq 60 ]]; then
        printf 'PostgreSQL container did not become ready.\n' >&2
        exit 1
    fi
    sleep 1
done

# Rails application initializers query the selected database while booting.
docker exec "$CONTAINER_ID" createdb -U postgres ffcrm_baseline

(
    cd "$REPO_ROOT"
    DATABASE_URL="postgres://postgres:postgres@127.0.0.1:$PORT/ffcrm_baseline" \
        RAILS_ENV=development \
        bundle exec rails db:create db:schema:load
)

docker exec "$CONTAINER_ID" pg_dump -U postgres --schema-only --no-owner --no-privileges ffcrm_baseline \
    > "$TEMP_DIR/rails_schema.sql"

sed -i \
    -e '/^\\restrict[[:space:]]/d' \
    -e '/^\\unrestrict[[:space:]]/d' \
    -e '/^-- Dumped from database version /d' \
    -e '/^-- Dumped by pg_dump version /d' \
    "$TEMP_DIR/rails_schema.sql"

MIGRATION_VALUES="$(docker exec "$CONTAINER_ID" psql -U postgres -d ffcrm_baseline -At \
    -c 'SELECT version FROM schema_migrations ORDER BY version' |
    awk 'BEGIN { separator = "" } { printf "%s('\''%s'\'')", separator, $0; separator = "," } END { print "" }')"
if [[ -z "$MIGRATION_VALUES" ]]; then
    printf 'No Rails schema_migrations versions found in the generated database.\n' >&2
    exit 1
fi
printf '\nINSERT INTO public.schema_migrations (version) VALUES %s;\n' "$MIGRATION_VALUES" \
    >> "$TEMP_DIR/rails_schema.sql"

FIXTURE_OUTPUT="$TEMP_DIR/rails_schema.sql"
MIGRATION_OUTPUT="$TEMP_DIR/V1__baseline_rails_schema.sql"
sed '/^SELECT pg_catalog.set_config('\''search_path'\'', '\'''\'', false);$/d' \
    "$TEMP_DIR/rails_schema.sql" > "$TEMP_DIR/flyway_schema_body.sql"
{
    printf '%s\n' \
        "-- Generated by spring/scripts/generate-baseline.sh from db/schema.rb version $SCHEMA_VERSION." \
        '-- schema_migrations and ar_internal_metadata are intentionally kept so Rails and Spring can share the' \
        '-- database during the strangler window; schema_migrations is pre-populated so Rails will not re-run' \
        '-- migrations, and a Spring-created database is indistinguishable from rails db:schema:load.' \
        '-- V1 must never be edited after release; schema changes belong in additive V2+ migrations.' \
        '-- Production cf_* columns from the AB-262 dump are not present in db/schema.rb.'
    cat "$TEMP_DIR/flyway_schema_body.sql"
} > "$MIGRATION_OUTPUT"

if [[ "$CHECK_MODE" == true ]]; then
    DIFF_FOUND=false
    if ! diff -u "$FIXTURE" "$FIXTURE_OUTPUT"; then
        DIFF_FOUND=true
    fi
    if ! diff -u "$MIGRATION" "$MIGRATION_OUTPUT"; then
        DIFF_FOUND=true
    fi
    if [[ "$DIFF_FOUND" == true ]]; then
        printf '%s\n' \
            'Rails baseline drift detected.' \
            'Before V1 is released, rerun spring/scripts/generate-baseline.sh to regenerate.' \
            'After V1 has been applied to any shared database, never regenerate V1; add an additive V2+__*.sql migration and refresh only the Rails fixture.' \
            >&2
        exit 1
    fi
    printf 'Rails baseline files match the current db/schema.rb output.\n'
else
    mkdir -p "$(dirname "$FIXTURE")" "$(dirname "$MIGRATION")"
    cp "$FIXTURE_OUTPUT" "$FIXTURE"
    cp "$MIGRATION_OUTPUT" "$MIGRATION"
    printf 'Generated %s and %s.\n' \
        "${FIXTURE#"$REPO_ROOT/"}" \
        "${MIGRATION#"$REPO_ROOT/"}"
fi
