#!/usr/bin/env bash
# Regenerates spring/src/test/resources/db/rails/rails_seed_data.sql: a pg_dump of a database Rails seeded with
# lib/tasks/ffcrm/seed_fixture.rake. The Spring data-fidelity tests load this on top of rails_schema.sql.
# Not byte-for-byte reproducible (Devise salts/tokens are random), so regenerate deliberately and review the diff.
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/../.." && pwd)"
FIXTURE="$REPO_ROOT/spring/src/test/resources/db/rails/rails_seed_data.sql"

if [[ "$#" -gt 0 ]]; then
    printf 'Usage: %s\n' "$0" >&2
    exit 2
fi

TEMP_DIR="$(mktemp -d)"
CONTAINER_ID=""
CREATED_DATABASE_YML=false

cleanup() {
    if [[ -n "$CONTAINER_ID" ]]; then
        docker rm -f "$CONTAINER_ID" >/dev/null 2>&1 || true
    fi
    if [[ "$CREATED_DATABASE_YML" == true ]]; then
        rm -f "$REPO_ROOT/config/database.yml"
    fi
    rm -rf "$TEMP_DIR"
}
trap cleanup EXIT

if [[ ! -f "$REPO_ROOT/config/database.yml" ]]; then
    cp "$REPO_ROOT/config/database.postgres.yml" "$REPO_ROOT/config/database.yml"
    CREATED_DATABASE_YML=true
fi

CONTAINER_ID="$(docker run -d \
    -e POSTGRES_PASSWORD=postgres \
    -p 127.0.0.1::5432 \
    "${PG_IMAGE:-postgres:16}")"
PORT="$(docker port "$CONTAINER_ID" 5432/tcp | sed 's/.*://')"

for attempt in $(seq 1 60); do
    if docker exec "$CONTAINER_ID" pg_isready -U postgres >/dev/null 2>&1; then
        break
    fi
    if [[ "$attempt" -eq 60 ]]; then
        printf 'PostgreSQL container did not become ready.\n' >&2
        exit 1
    fi
    sleep 1
done

docker exec "$CONTAINER_ID" createdb -U postgres ffcrm_seed

(
    cd "$REPO_ROOT"
    DATABASE_URL="postgres://postgres:postgres@127.0.0.1:$PORT/ffcrm_seed" \
        RAILS_ENV=development \
        bundle exec rails db:schema:load ffcrm:migration:seed_fixture
)

docker exec "$CONTAINER_ID" pg_dump -U postgres \
    --data-only --column-inserts --no-owner --no-privileges \
    --exclude-table=schema_migrations \
    --exclude-table=ar_internal_metadata \
    --exclude-table='solid_queue_*' \
    --exclude-table='active_storage_*' \
    --exclude-table=action_text_rich_texts \
    --exclude-table=sessions \
    ffcrm_seed > "$TEMP_DIR/rails_seed_data.sql"

sed -i \
    -e '/^\\restrict[[:space:]]/d' \
    -e '/^\\unrestrict[[:space:]]/d' \
    -e '/^-- Dumped from database version /d' \
    -e '/^-- Dumped by pg_dump version /d' \
    "$TEMP_DIR/rails_seed_data.sql"

{
    printf '%s\n' \
        '-- Generated by spring/scripts/generate-seed-fixture.sh from lib/tasks/ffcrm/seed_fixture.rake.' \
        '-- Rails-written rows for every application table; loaded on top of rails_schema.sql by the Spring' \
        '-- data-fidelity tests. Regenerate (do not hand-edit) when the seed task or the Rails schema changes.'
    cat "$TEMP_DIR/rails_seed_data.sql"
} > "$FIXTURE"

printf 'Generated %s.\n' "${FIXTURE#"$REPO_ROOT/"}"
