-- Generated by ffcrm:migration:entity_fixture.
-- Regenerate with: FFCRM_ENTITY_FIXTURE=1 SECRET_KEY_BASE=entity-fixture-only-secret-key-base-0123456789abcdef bundle exec rake ffcrm:migration:entity_fixture

INSERT INTO public."account_contacts" ("id", "account_id", "contact_id", "deleted_at", "created_at", "updated_at") VALUES ('1', '1', '1', '2025-01-02 03:04:31 UTC', '2025-01-02 03:04:08 UTC', '2025-01-02 03:04:08 UTC');
SELECT pg_catalog.setval('public.account_contacts_id_seq', 1, true);
INSERT INTO public."account_opportunities" ("id", "account_id", "opportunity_id", "deleted_at", "created_at", "updated_at") VALUES ('1', '1', '1', '2025-01-02 03:04:31 UTC', '2025-01-02 03:04:08 UTC', '2025-01-02 03:04:08 UTC');
SELECT pg_catalog.setval('public.account_opportunities_id_seq', 1, true);
INSERT INTO public."accounts" ("id", "user_id", "assigned_to", "name", "access", "website", "toll_free_phone", "phone", "fax", "deleted_at", "created_at", "updated_at", "email", "background_info", "rating", "category", "subscribed_users", "contacts_count", "opportunities_count", "wikidata_id", "latitude", "longitude", "blog", "linkedin", "facebook", "twitter", "bluesky", "instagram", "mastodon") VALUES ('1', '1', '2', 'Entity Fixture Account', 'Shared', NULL, NULL, NULL, NULL, '2025-01-02 03:04:31 UTC', '2025-01-02 03:04:08 UTC', '2025-01-02 03:04:31 UTC', NULL, 'Versioned fixture update', '0', NULL, '---
- 2
- 1
- 1
', '1', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."accounts" ("id", "user_id", "assigned_to", "name", "access", "website", "toll_free_phone", "phone", "fax", "deleted_at", "created_at", "updated_at", "email", "background_info", "rating", "category", "subscribed_users", "contacts_count", "opportunities_count", "wikidata_id", "latitude", "longitude", "blog", "linkedin", "facebook", "twitter", "bluesky", "instagram", "mastodon") VALUES ('2', '1', NULL, 'Empty subscribers fixture', 'Public', NULL, NULL, NULL, NULL, NULL, '2025-01-02 03:04:31 UTC', '2025-01-02 03:04:31 UTC', NULL, NULL, '0', NULL, NULL, '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."accounts" ("id", "user_id", "assigned_to", "name", "access", "website", "toll_free_phone", "phone", "fax", "deleted_at", "created_at", "updated_at", "email", "background_info", "rating", "category", "subscribed_users", "contacts_count", "opportunities_count", "wikidata_id", "latitude", "longitude", "blog", "linkedin", "facebook", "twitter", "bluesky", "instagram", "mastodon") VALUES ('3', '1', NULL, 'Legacy empty subscribers fixture', 'Public', NULL, NULL, NULL, NULL, NULL, '2025-01-02 03:04:31 UTC', '2025-01-02 03:04:31 UTC', NULL, NULL, '0', NULL, '--- []
', '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
SELECT pg_catalog.setval('public.accounts_id_seq', 3, true);
INSERT INTO public."activities" ("id", "user_id", "subject_type", "subject_id", "action", "info", "private", "created_at", "updated_at") VALUES ('1', '1', 'Account', '1', 'created', 'Fixture activity', 'false', '2025-01-02 03:04:31 UTC', '2025-01-02 03:04:31 UTC');
SELECT pg_catalog.setval('public.activities_id_seq', 1, true);
INSERT INTO public."addresses" ("id", "street1", "street2", "city", "state", "zipcode", "country", "full_address", "address_type", "addressable_type", "addressable_id", "created_at", "updated_at", "deleted_at") VALUES ('1', '1 Fixture Street', NULL, 'Fixture City', 'CA', '90210', 'US', NULL, 'Business', 'Account', '1', '2025-01-02 03:04:23 UTC', '2025-01-02 03:04:23 UTC', '2025-01-02 03:04:31 UTC');
INSERT INTO public."addresses" ("id", "street1", "street2", "city", "state", "zipcode", "country", "full_address", "address_type", "addressable_type", "addressable_id", "created_at", "updated_at", "deleted_at") VALUES ('2', '1 Fixture Street', NULL, 'Fixture City', 'CA', '90210', 'US', NULL, 'Billing', 'Account', '1', '2025-01-02 03:04:24 UTC', '2025-01-02 03:04:24 UTC', NULL);
INSERT INTO public."addresses" ("id", "street1", "street2", "city", "state", "zipcode", "country", "full_address", "address_type", "addressable_type", "addressable_id", "created_at", "updated_at", "deleted_at") VALUES ('3', '1 Fixture Street', NULL, 'Fixture City', 'CA', '90210', 'US', NULL, 'Shipping', 'Account', '1', '2025-01-02 03:04:25 UTC', '2025-01-02 03:04:25 UTC', NULL);
INSERT INTO public."addresses" ("id", "street1", "street2", "city", "state", "zipcode", "country", "full_address", "address_type", "addressable_type", "addressable_id", "created_at", "updated_at", "deleted_at") VALUES ('4', '1 Fixture Street', NULL, 'Fixture City', 'CA', '90210', 'US', NULL, 'Business', 'Contact', '1', '2025-01-02 03:04:26 UTC', '2025-01-02 03:04:26 UTC', NULL);
INSERT INTO public."addresses" ("id", "street1", "street2", "city", "state", "zipcode", "country", "full_address", "address_type", "addressable_type", "addressable_id", "created_at", "updated_at", "deleted_at") VALUES ('5', '1 Fixture Street', NULL, 'Fixture City', 'CA', '90210', 'US', NULL, 'Billing', 'Contact', '1', '2025-01-02 03:04:27 UTC', '2025-01-02 03:04:27 UTC', NULL);
INSERT INTO public."addresses" ("id", "street1", "street2", "city", "state", "zipcode", "country", "full_address", "address_type", "addressable_type", "addressable_id", "created_at", "updated_at", "deleted_at") VALUES ('6', '1 Fixture Street', NULL, 'Fixture City', 'CA', '90210', 'US', NULL, 'Shipping', 'Contact', '1', '2025-01-02 03:04:28 UTC', '2025-01-02 03:04:28 UTC', NULL);
INSERT INTO public."addresses" ("id", "street1", "street2", "city", "state", "zipcode", "country", "full_address", "address_type", "addressable_type", "addressable_id", "created_at", "updated_at", "deleted_at") VALUES ('7', '1 Fixture Street', NULL, 'Fixture City', 'CA', '90210', 'US', NULL, 'Business', 'Lead', '1', '2025-01-02 03:04:29 UTC', '2025-01-02 03:04:29 UTC', NULL);
INSERT INTO public."addresses" ("id", "street1", "street2", "city", "state", "zipcode", "country", "full_address", "address_type", "addressable_type", "addressable_id", "created_at", "updated_at", "deleted_at") VALUES ('8', '1 Fixture Street', NULL, 'Fixture City', 'CA', '90210', 'US', NULL, 'Billing', 'Lead', '1', '2025-01-02 03:04:30 UTC', '2025-01-02 03:04:30 UTC', NULL);
INSERT INTO public."addresses" ("id", "street1", "street2", "city", "state", "zipcode", "country", "full_address", "address_type", "addressable_type", "addressable_id", "created_at", "updated_at", "deleted_at") VALUES ('9', '1 Fixture Street', NULL, 'Fixture City', 'CA', '90210', 'US', NULL, 'Shipping', 'Lead', '1', '2025-01-02 03:04:31 UTC', '2025-01-02 03:04:31 UTC', NULL);
SELECT pg_catalog.setval('public.addresses_id_seq', 9, true);
INSERT INTO public."avatars" ("id", "user_id", "entity_type", "entity_id", "image_file_size", "image_file_name", "image_content_type", "created_at", "updated_at") VALUES ('1', '1', 'User', '1', NULL, NULL, NULL, '2025-01-02 03:04:31 UTC', '2025-01-02 03:04:31 UTC');
INSERT INTO public."avatars" ("id", "user_id", "entity_type", "entity_id", "image_file_size", "image_file_name", "image_content_type", "created_at", "updated_at") VALUES ('2', '1', 'Contact', '1', NULL, NULL, NULL, '2025-01-02 03:04:31 UTC', '2025-01-02 03:04:31 UTC');
SELECT pg_catalog.setval('public.avatars_id_seq', 2, true);
INSERT INTO public."campaigns" ("id", "user_id", "assigned_to", "name", "access", "status", "budget", "target_leads", "target_conversion", "target_revenue", "leads_count", "opportunities_count", "revenue", "starts_on", "ends_on", "objectives", "deleted_at", "created_at", "updated_at", "background_info", "subscribed_users") VALUES ('1', '1', '2', 'Entity Fixture Campaign', 'Public', NULL, NULL, NULL, NULL, NULL, '1', '1', NULL, NULL, NULL, NULL, '2025-01-02 03:04:31 UTC', '2025-01-02 03:04:06 UTC', '2025-01-02 03:04:15 UTC', NULL, '---
- 2
- 1
- 1
');
SELECT pg_catalog.setval('public.campaigns_id_seq', 1, true);
INSERT INTO public."comments" ("id", "user_id", "commentable_type", "commentable_id", "private", "title", "comment", "created_at", "updated_at", "state") VALUES ('1', '1', 'Account', '1', NULL, '', 'Fixture comment', '2025-01-02 03:04:14 UTC', '2025-01-02 03:04:14 UTC', 'Expanded');
INSERT INTO public."comments" ("id", "user_id", "commentable_type", "commentable_id", "private", "title", "comment", "created_at", "updated_at", "state") VALUES ('2', '1', 'Campaign', '1', NULL, '', 'Fixture comment', '2025-01-02 03:04:15 UTC', '2025-01-02 03:04:15 UTC', 'Expanded');
INSERT INTO public."comments" ("id", "user_id", "commentable_type", "commentable_id", "private", "title", "comment", "created_at", "updated_at", "state") VALUES ('3', '1', 'Contact', '1', NULL, '', 'Fixture comment', '2025-01-02 03:04:16 UTC', '2025-01-02 03:04:16 UTC', 'Expanded');
INSERT INTO public."comments" ("id", "user_id", "commentable_type", "commentable_id", "private", "title", "comment", "created_at", "updated_at", "state") VALUES ('4', '1', 'Lead', '1', NULL, '', 'Fixture comment', '2025-01-02 03:04:17 UTC', '2025-01-02 03:04:17 UTC', 'Expanded');
INSERT INTO public."comments" ("id", "user_id", "commentable_type", "commentable_id", "private", "title", "comment", "created_at", "updated_at", "state") VALUES ('5', '1', 'Opportunity', '1', NULL, '', 'Fixture comment', '2025-01-02 03:04:18 UTC', '2025-01-02 03:04:18 UTC', 'Expanded');
INSERT INTO public."comments" ("id", "user_id", "commentable_type", "commentable_id", "private", "title", "comment", "created_at", "updated_at", "state") VALUES ('6', '1', 'Task', '1', NULL, '', 'Fixture comment', '2025-01-02 03:04:19 UTC', '2025-01-02 03:04:19 UTC', 'Expanded');
SELECT pg_catalog.setval('public.comments_id_seq', 6, true);
INSERT INTO public."contact_opportunities" ("id", "contact_id", "opportunity_id", "role", "deleted_at", "created_at", "updated_at") VALUES ('1', '1', '1', 'Decision Maker', '2025-01-02 03:04:31 UTC', '2025-01-02 03:04:08 UTC', '2025-01-02 03:04:08 UTC');
SELECT pg_catalog.setval('public.contact_opportunities_id_seq', 1, true);
INSERT INTO public."contacts" ("id", "user_id", "lead_id", "assigned_to", "reports_to", "first_name", "last_name", "access", "title", "department", "source", "email", "alt_email", "phone", "mobile", "fax", "blog", "linkedin", "facebook", "twitter", "born_on", "do_not_call", "deleted_at", "created_at", "updated_at", "background_info", "subscribed_users", "zoom", "teams", "signal", "instagram", "mastodon", "bluesky") VALUES ('1', '1', '1', '2', '2', 'Fixture', 'Contact', 'Public', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'false', '2025-01-02 03:04:31 UTC', '2025-01-02 03:04:07 UTC', '2025-01-02 03:04:16 UTC', NULL, '---
- 1
', NULL, NULL, NULL, NULL, NULL, NULL);
SELECT pg_catalog.setval('public.contacts_id_seq', 1, true);
INSERT INTO public."emails" ("id", "imap_message_id", "user_id", "mediator_type", "mediator_id", "sent_from", "sent_to", "cc", "bcc", "subject", "body", "header", "sent_at", "received_at", "deleted_at", "created_at", "updated_at", "state") VALUES ('1', 'fixture-account@example.test', '1', 'Account', '1', 'owner@example.test', 'assignee@example.test', NULL, NULL, 'Fixture email', 'Rails-created email', NULL, NULL, NULL, '2025-01-02 03:04:31 UTC', '2025-01-02 03:04:20 UTC', '2025-01-02 03:04:20 UTC', 'Expanded');
INSERT INTO public."emails" ("id", "imap_message_id", "user_id", "mediator_type", "mediator_id", "sent_from", "sent_to", "cc", "bcc", "subject", "body", "header", "sent_at", "received_at", "deleted_at", "created_at", "updated_at", "state") VALUES ('2', 'fixture-contact@example.test', '1', 'Contact', '1', 'owner@example.test', 'assignee@example.test', NULL, NULL, 'Fixture email', 'Rails-created email', NULL, NULL, NULL, NULL, '2025-01-02 03:04:21 UTC', '2025-01-02 03:04:21 UTC', 'Expanded');
INSERT INTO public."emails" ("id", "imap_message_id", "user_id", "mediator_type", "mediator_id", "sent_from", "sent_to", "cc", "bcc", "subject", "body", "header", "sent_at", "received_at", "deleted_at", "created_at", "updated_at", "state") VALUES ('3', 'fixture-lead@example.test', '1', 'Lead', '1', 'owner@example.test', 'assignee@example.test', NULL, NULL, 'Fixture email', 'Rails-created email', NULL, NULL, NULL, NULL, '2025-01-02 03:04:22 UTC', '2025-01-02 03:04:22 UTC', 'Expanded');
SELECT pg_catalog.setval('public.emails_id_seq', 3, true);
INSERT INTO public."field_groups" ("id", "name", "label", "position", "hint", "created_at", "updated_at", "tag_id", "klass_name") VALUES ('1', 'Fixture Fields', 'Fixture Fields', NULL, NULL, '2025-01-02 03:04:31 UTC', '2025-01-02 03:04:31 UTC', '1', 'Account');
SELECT pg_catalog.setval('public.field_groups_id_seq', 1, true);
INSERT INTO public."fields" ("id", "type", "field_group_id", "position", "name", "label", "hint", "placeholder", "as", "collection", "disabled", "required", "maxlength", "created_at", "updated_at", "pair_id", "settings", "minlength", "pattern", "autofocus", "autocomplete", "list", "multiple", "title") VALUES ('1', 'CoreField', '1', '1', 'fixture_core', 'Core fixture field', NULL, NULL, 'string', NULL, NULL, NULL, NULL, '2025-01-02 03:04:31 UTC', '2025-01-02 03:04:31 UTC', NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."fields" ("id", "type", "field_group_id", "position", "name", "label", "hint", "placeholder", "as", "collection", "disabled", "required", "maxlength", "created_at", "updated_at", "pair_id", "settings", "minlength", "pattern", "autofocus", "autocomplete", "list", "multiple", "title") VALUES ('2', 'CustomField', '1', '2', 'fixture_custom', 'Custom fixture field', NULL, NULL, 'check_boxes', '---
- one
- two
', NULL, NULL, NULL, '2025-01-02 03:04:31 UTC', '2025-01-02 03:04:31 UTC', NULL, '--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
multiple: true
', '0', NULL, NULL, NULL, NULL, NULL, NULL);
SELECT pg_catalog.setval('public.fields_id_seq', 2, true);
INSERT INTO public."groups" ("id", "name", "created_at", "updated_at") VALUES ('1', 'Entity Fixture Group', '2025-01-02 03:04:05 UTC', '2025-01-02 03:04:05 UTC');
SELECT pg_catalog.setval('public.groups_id_seq', 1, true);
INSERT INTO public."groups_users" ("group_id", "user_id") VALUES ('1', '1');
INSERT INTO public."leads" ("id", "user_id", "campaign_id", "assigned_to", "first_name", "last_name", "access", "title", "company", "source", "status", "referred_by", "email", "alt_email", "phone", "mobile", "blog", "linkedin", "facebook", "twitter", "rating", "do_not_call", "deleted_at", "created_at", "updated_at", "background_info", "subscribed_users", "zoom", "teams", "signal", "instagram", "mastodon", "bluesky") VALUES ('1', '1', '1', '2', 'Fixture', 'Lead', 'Public', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', 'false', '2025-01-02 03:04:31 UTC', '2025-01-02 03:04:06 UTC', '2025-01-02 03:04:17 UTC', NULL, '---
- 1
', NULL, NULL, NULL, NULL, NULL, NULL);
SELECT pg_catalog.setval('public.leads_id_seq', 1, true);
INSERT INTO public."lists" ("id", "name", "url", "created_at", "updated_at", "user_id") VALUES ('1', 'Entity Fixture List', '/accounts', '2025-01-02 03:04:31 UTC', '2025-01-02 03:04:31 UTC', '1');
SELECT pg_catalog.setval('public.lists_id_seq', 1, true);
INSERT INTO public."opportunities" ("id", "user_id", "campaign_id", "assigned_to", "name", "access", "source", "stage", "probability", "amount", "discount", "closes_on", "deleted_at", "created_at", "updated_at", "background_info", "subscribed_users") VALUES ('1', '1', '1', '2', 'Entity Fixture Opportunity', 'Public', NULL, NULL, NULL, NULL, NULL, NULL, '2025-01-02 03:04:31 UTC', '2025-01-02 03:04:08 UTC', '2025-01-02 03:04:18 UTC', NULL, '---
- 1
');
SELECT pg_catalog.setval('public.opportunities_id_seq', 1, true);
INSERT INTO public."permissions" ("id", "user_id", "asset_type", "asset_id", "created_at", "updated_at", "group_id") VALUES ('1', '2', 'Account', '1', '2025-01-02 03:04:08 UTC', '2025-01-02 03:04:08 UTC', NULL);
INSERT INTO public."permissions" ("id", "user_id", "asset_type", "asset_id", "created_at", "updated_at", "group_id") VALUES ('2', NULL, 'Account', '1', '2025-01-02 03:04:08 UTC', '2025-01-02 03:04:08 UTC', '1');
SELECT pg_catalog.setval('public.permissions_id_seq', 2, true);
INSERT INTO public."preferences" ("id", "user_id", "name", "value", "created_at", "updated_at") VALUES ('1', '1', 'fixture_short', 'ImFsbCI=
', '2025-01-02 03:04:31 UTC', '2025-01-02 03:04:31 UTC');
INSERT INTO public."preferences" ("id", "user_id", "name", "value", "created_at", "updated_at") VALUES ('2', '1', 'fixture_hash', 'eyJhbHBoYSI6MSwiYmV0YSI6W3RydWUsZmFsc2VdfQ==
', '2025-01-02 03:04:31 UTC', '2025-01-02 03:04:31 UTC');
INSERT INTO public."preferences" ("id", "user_id", "name", "value", "created_at", "updated_at") VALUES ('3', '1', 'fixture_long', 'ImxvbmcgcHJlZmVyZW5jZSBsb25nIHByZWZlcmVuY2UgbG9uZyBwcmVmZXJl
bmNlIGxvbmcgcHJlZmVyZW5jZSBsb25nIHByZWZlcmVuY2UgbG9uZyBwcmVm
ZXJlbmNlIGxvbmcgcHJlZmVyZW5jZSBsb25nIHByZWZlcmVuY2UgbG9uZyBw
cmVmZXJlbmNlIGxvbmcgcHJlZmVyZW5jZSBsb25nIHByZWZlcmVuY2UgbG9u
ZyBwcmVmZXJlbmNlICI=
', '2025-01-02 03:04:31 UTC', '2025-01-02 03:04:31 UTC');
INSERT INTO public."preferences" ("id", "user_id", "name", "value", "created_at", "updated_at") VALUES ('4', '1', 'fixture_unicode', 'ImNhZsOpLeaXpeacrOiqni3wn5SQIg==
', '2025-01-02 03:04:31 UTC', '2025-01-02 03:04:31 UTC');
SELECT pg_catalog.setval('public.preferences_id_seq', 4, true);
INSERT INTO public."research_tools" ("id", "name", "url_template", "enabled", "created_at", "updated_at") VALUES ('1', 'Fixture Research', 'https://example.test/%s', 'false', '2025-01-02 03:04:31 UTC', '2025-01-02 03:04:31 UTC');
SELECT pg_catalog.setval('public.research_tools_id_seq', 1, true);
INSERT INTO public."settings" ("id", "name", "value", "created_at", "updated_at") VALUES ('1', 'fixture_string', '--- string value
', '2025-01-02 03:04:31 UTC', '2025-01-02 03:04:31 UTC');
INSERT INTO public."settings" ("id", "name", "value", "created_at", "updated_at") VALUES ('2', 'fixture_symbols', '---
- :one
- :two
', '2025-01-02 03:04:31 UTC', '2025-01-02 03:04:31 UTC');
INSERT INTO public."settings" ("id", "name", "value", "created_at", "updated_at") VALUES ('3', 'fixture_hash', '---
nested:
- value
- 2
', '2025-01-02 03:04:31 UTC', '2025-01-02 03:04:31 UTC');
SELECT pg_catalog.setval('public.settings_id_seq', 3, true);
INSERT INTO public."taggings" ("id", "tag_id", "taggable_id", "tagger_id", "tagger_type", "taggable_type", "context", "created_at") VALUES ('1', '1', '1', NULL, NULL, 'Account', 'tags', '2025-01-02 03:04:31 UTC');
INSERT INTO public."taggings" ("id", "tag_id", "taggable_id", "tagger_id", "tagger_type", "taggable_type", "context", "created_at") VALUES ('2', '2', '1', NULL, NULL, 'Account', 'tags', '2025-01-02 03:04:31 UTC');
SELECT pg_catalog.setval('public.taggings_id_seq', 2, true);
INSERT INTO public."tags" ("id", "name", "taggings_count") VALUES ('1', 'entity-fixture', '1');
INSERT INTO public."tags" ("id", "name", "taggings_count") VALUES ('2', 'domain-model', '1');
SELECT pg_catalog.setval('public.tags_id_seq', 2, true);
INSERT INTO public."tasks" ("id", "user_id", "assigned_to", "completed_by", "name", "asset_type", "asset_id", "priority", "category", "bucket", "due_at", "completed_at", "deleted_at", "created_at", "updated_at", "background_info", "subscribed_users") VALUES ('1', '1', '2', NULL, 'Task for Account', 'Account', '1', NULL, NULL, NULL, NULL, NULL, '2025-01-02 03:04:31 UTC', '2025-01-02 03:04:09 UTC', '2025-01-02 03:04:19 UTC', NULL, '---
- 1
- 2
- 1
');
INSERT INTO public."tasks" ("id", "user_id", "assigned_to", "completed_by", "name", "asset_type", "asset_id", "priority", "category", "bucket", "due_at", "completed_at", "deleted_at", "created_at", "updated_at", "background_info", "subscribed_users") VALUES ('2', '1', '2', NULL, 'Task for Campaign', 'Campaign', '1', NULL, NULL, NULL, NULL, NULL, NULL, '2025-01-02 03:04:10 UTC', '2025-01-02 03:04:10 UTC', NULL, '---
- 1
- 2
');
INSERT INTO public."tasks" ("id", "user_id", "assigned_to", "completed_by", "name", "asset_type", "asset_id", "priority", "category", "bucket", "due_at", "completed_at", "deleted_at", "created_at", "updated_at", "background_info", "subscribed_users") VALUES ('3', '1', '2', NULL, 'Task for Contact', 'Contact', '1', NULL, NULL, NULL, NULL, NULL, NULL, '2025-01-02 03:04:11 UTC', '2025-01-02 03:04:11 UTC', NULL, '---
- 1
- 2
');
INSERT INTO public."tasks" ("id", "user_id", "assigned_to", "completed_by", "name", "asset_type", "asset_id", "priority", "category", "bucket", "due_at", "completed_at", "deleted_at", "created_at", "updated_at", "background_info", "subscribed_users") VALUES ('4', '1', '2', NULL, 'Task for Lead', 'Lead', '1', NULL, NULL, NULL, NULL, NULL, NULL, '2025-01-02 03:04:12 UTC', '2025-01-02 03:04:12 UTC', NULL, '---
- 1
- 2
');
INSERT INTO public."tasks" ("id", "user_id", "assigned_to", "completed_by", "name", "asset_type", "asset_id", "priority", "category", "bucket", "due_at", "completed_at", "deleted_at", "created_at", "updated_at", "background_info", "subscribed_users") VALUES ('5', '1', '2', NULL, 'Task for Opportunity', 'Opportunity', '1', NULL, NULL, NULL, NULL, NULL, NULL, '2025-01-02 03:04:13 UTC', '2025-01-02 03:04:13 UTC', NULL, '---
- 1
- 2
');
INSERT INTO public."tasks" ("id", "user_id", "assigned_to", "completed_by", "name", "asset_type", "asset_id", "priority", "category", "bucket", "due_at", "completed_at", "deleted_at", "created_at", "updated_at", "background_info", "subscribed_users") VALUES ('6', '1', NULL, NULL, 'Standalone fixture task', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-01-02 03:04:13 UTC', '2025-01-02 03:04:13 UTC', NULL, NULL);
INSERT INTO public."tasks" ("id", "user_id", "assigned_to", "completed_by", "name", "asset_type", "asset_id", "priority", "category", "bucket", "due_at", "completed_at", "deleted_at", "created_at", "updated_at", "background_info", "subscribed_users") VALUES ('7', '1', NULL, NULL, 'Recreated standalone fixture task', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-01-02 03:04:13 UTC', '2025-01-02 03:04:13 UTC', NULL, NULL);
INSERT INTO public."tasks" ("id", "user_id", "assigned_to", "completed_by", "name", "asset_type", "asset_id", "priority", "category", "bucket", "due_at", "completed_at", "deleted_at", "created_at", "updated_at", "background_info", "subscribed_users") VALUES ('8', '1', NULL, NULL, 'Completed fixture task', 'Contact', '1', NULL, NULL, NULL, NULL, '2025-01-02 03:04:13 UTC', NULL, '2025-01-02 03:04:13 UTC', '2025-01-02 03:04:13 UTC', NULL, NULL);
SELECT pg_catalog.setval('public.tasks_id_seq', 8, true);
INSERT INTO public."users" ("id", "username", "email", "first_name", "last_name", "title", "company", "alt_email", "phone", "mobile", "google", "encrypted_password", "password_salt", "last_sign_in_at", "current_sign_in_at", "last_sign_in_ip", "current_sign_in_ip", "sign_in_count", "deleted_at", "created_at", "updated_at", "admin", "suspended_at", "unconfirmed_email", "reset_password_token", "reset_password_sent_at", "remember_token", "remember_created_at", "authentication_token", "confirmation_token", "confirmed_at", "confirmation_sent_at", "subscribe_to_comment_replies", "receive_assigned_notifications", "zoom", "teams", "signal", "instagram", "facebook", "mastodon", "bluesky", "twitter", "linkedin", "blog") VALUES ('1', 'entity_owner', 'owner@example.test', 'Entity', 'Owner', NULL, NULL, NULL, NULL, NULL, NULL, 'fixed-encrypted-owner', 'fixed-salt-owner', NULL, NULL, NULL, NULL, '0', NULL, '2025-01-02 03:04:05 UTC', '2025-01-02 03:04:05 UTC', 'false', NULL, NULL, 'fixed-reset-owner', NULL, 'fixed-remember-owner', NULL, 'fixed-auth-owner', 'fixed-confirm-owner', '2025-01-02 03:04:05 UTC', NULL, 'true', 'true', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."users" ("id", "username", "email", "first_name", "last_name", "title", "company", "alt_email", "phone", "mobile", "google", "encrypted_password", "password_salt", "last_sign_in_at", "current_sign_in_at", "last_sign_in_ip", "current_sign_in_ip", "sign_in_count", "deleted_at", "created_at", "updated_at", "admin", "suspended_at", "unconfirmed_email", "reset_password_token", "reset_password_sent_at", "remember_token", "remember_created_at", "authentication_token", "confirmation_token", "confirmed_at", "confirmation_sent_at", "subscribe_to_comment_replies", "receive_assigned_notifications", "zoom", "teams", "signal", "instagram", "facebook", "mastodon", "bluesky", "twitter", "linkedin", "blog") VALUES ('2', 'entity_assignee', 'assignee@example.test', 'Entity', 'Assignee', NULL, NULL, NULL, NULL, NULL, NULL, 'fixed-encrypted-assignee', 'fixed-salt-assignee', NULL, NULL, NULL, NULL, '0', NULL, '2025-01-02 03:04:05 UTC', '2025-01-02 03:04:05 UTC', 'false', NULL, NULL, 'fixed-reset-assignee', NULL, 'fixed-remember-assignee', NULL, 'fixed-auth-assignee', 'fixed-confirm-assignee', '2025-01-02 03:04:05 UTC', NULL, 'true', 'true', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
SELECT pg_catalog.setval('public.users_id_seq', 2, true);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('1', 'User', '1', 'create', '1', NULL, '2025-01-02 03:04:05 UTC', '---
id:
-
- 1
username:
- ''''
- entity_owner
email:
-
- owner@example.test
first_name:
-
- Entity
last_name:
-
- Owner
encrypted_password:
- ''''
- fixed-encrypted-owner
password_salt:
- ''''
- fixed-salt-owner
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:05.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:05.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:05.000000000 Z
reset_password_token:
-
- fixed-reset-owner
remember_token:
-
- fixed-remember-owner
authentication_token:
-
- fixed-auth-owner
confirmation_token:
-
- fixed-confirm-owner
confirmed_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: 2025-01-02 03:04:05.000000000 Z
  zone: *2
  time: 2025-01-02 03:04:05.000000000 Z
', NULL, NULL, NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('2', 'User', '2', 'create', '1', NULL, '2025-01-02 03:04:05 UTC', '---
id:
-
- 2
username:
- ''''
- entity_assignee
email:
-
- assignee@example.test
first_name:
-
- Entity
last_name:
-
- Assignee
encrypted_password:
- ''''
- fixed-encrypted-assignee
password_salt:
- ''''
- fixed-salt-assignee
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:05.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:05.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:05.000000000 Z
reset_password_token:
-
- fixed-reset-assignee
remember_token:
-
- fixed-remember-assignee
authentication_token:
-
- fixed-auth-assignee
confirmation_token:
-
- fixed-confirm-assignee
confirmed_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: 2025-01-02 03:04:05.000000000 Z
  zone: *2
  time: 2025-01-02 03:04:05.000000000 Z
', NULL, NULL, NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('3', 'Campaign', '1', 'create', '1', NULL, '2025-01-02 03:04:06 UTC', '---
id:
-
- 1
user_id:
-
- 1
assigned_to:
-
- 2
name:
- ''''
- Entity Fixture Campaign
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:06.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:06.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:06.000000000 Z
', NULL, NULL, NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('4', 'Lead', '1', 'create', '1', NULL, '2025-01-02 03:04:06 UTC', '---
id:
-
- 1
user_id:
-
- 1
campaign_id:
-
- 1
assigned_to:
-
- 2
first_name:
- ''''
- Fixture
last_name:
- ''''
- Lead
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:06.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:06.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:06.000000000 Z
', NULL, NULL, NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('5', 'Contact', '1', 'create', '1', NULL, '2025-01-02 03:04:07 UTC', '---
id:
-
- 1
user_id:
-
- 1
lead_id:
-
- 1
assigned_to:
-
- 2
reports_to:
-
- 2
first_name:
- ''''
- Fixture
last_name:
- ''''
- Contact
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:07.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:07.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:07.000000000 Z
', NULL, NULL, NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('6', 'Account', '1', 'create', '1', NULL, '2025-01-02 03:04:08 UTC', '---
id:
-
- 1
user_id:
-
- 1
assigned_to:
-
- 2
name:
- ''''
- Entity Fixture Account
access:
- Public
- Shared
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:08.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:08.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:08.000000000 Z
', NULL, NULL, NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('7', 'Opportunity', '1', 'create', '1', NULL, '2025-01-02 03:04:08 UTC', '---
id:
-
- 1
user_id:
-
- 1
campaign_id:
-
- 1
assigned_to:
-
- 2
name:
- ''''
- Entity Fixture Opportunity
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:08.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:08.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:08.000000000 Z
', NULL, NULL, NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('8', 'AccountContact', '1', 'create', '1', NULL, '2025-01-02 03:04:08 UTC', '---
account_id:
-
- 1
', '1', 'Contact', NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('9', 'AccountOpportunity', '1', 'create', '1', NULL, '2025-01-02 03:04:08 UTC', '---
id:
-
- 1
account_id:
-
- 1
opportunity_id:
-
- 1
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:08.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:08.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:08.000000000 Z
', NULL, NULL, NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('10', 'Task', '1', 'create', '1', NULL, '2025-01-02 03:04:09 UTC', '---
id:
-
- 1
user_id:
-
- 1
assigned_to:
-
- 2
name:
- ''''
- Task for Account
asset_type:
-
- Account
asset_id:
-
- 1
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:09.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:09.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:09.000000000 Z
', '1', 'Account', NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('11', 'Task', '2', 'create', '1', NULL, '2025-01-02 03:04:10 UTC', '---
id:
-
- 2
user_id:
-
- 1
assigned_to:
-
- 2
name:
- ''''
- Task for Campaign
asset_type:
-
- Campaign
asset_id:
-
- 1
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:10.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:10.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:10.000000000 Z
', '1', 'Campaign', NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('12', 'Task', '3', 'create', '1', NULL, '2025-01-02 03:04:11 UTC', '---
id:
-
- 3
user_id:
-
- 1
assigned_to:
-
- 2
name:
- ''''
- Task for Contact
asset_type:
-
- Contact
asset_id:
-
- 1
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:11.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:11.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:11.000000000 Z
', '1', 'Contact', NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('13', 'Task', '4', 'create', '1', NULL, '2025-01-02 03:04:12 UTC', '---
id:
-
- 4
user_id:
-
- 1
assigned_to:
-
- 2
name:
- ''''
- Task for Lead
asset_type:
-
- Lead
asset_id:
-
- 1
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:12.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:12.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:12.000000000 Z
', '1', 'Lead', NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('14', 'Task', '5', 'create', '1', NULL, '2025-01-02 03:04:13 UTC', '---
id:
-
- 5
user_id:
-
- 1
assigned_to:
-
- 2
name:
- ''''
- Task for Opportunity
asset_type:
-
- Opportunity
asset_id:
-
- 1
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:13.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:13.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:13.000000000 Z
', '1', 'Opportunity', NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('15', 'Task', '6', 'create', '1', NULL, '2025-01-02 03:04:13 UTC', '---
id:
-
- 6
user_id:
-
- 1
name:
- ''''
- Standalone fixture task
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:13.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:13.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:13.000000000 Z
', NULL, NULL, NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('16', 'Task', '7', 'create', '1', NULL, '2025-01-02 03:04:13 UTC', '---
id:
-
- 7
user_id:
-
- 1
name:
- ''''
- Destroy-version fixture task
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:13.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:13.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:13.000000000 Z
', NULL, NULL, NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('17', 'Task', '7', 'destroy', '1', '---
id: 7
user_id: 1
assigned_to:
completed_by:
name: Destroy-version fixture task
asset_type:
asset_id:
priority:
category:
bucket:
due_at:
completed_at:
deleted_at:
created_at: !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:13.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:13.000000000 Z
updated_at: !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:13.000000000 Z
background_info:
subscribed_users:
', '2025-01-02 03:04:13 UTC', '---
id:
- 7
-
user_id:
- 1
-
assigned_to:
-
-
completed_by:
-
-
name:
- Destroy-version fixture task
-
asset_type:
-
-
asset_id:
-
-
priority:
-
-
category:
-
-
bucket:
-
-
due_at:
-
-
completed_at:
-
-
deleted_at:
-
-
created_at:
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:13.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:13.000000000 Z
-
updated_at:
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:13.000000000 Z
-
background_info:
-
-
', NULL, NULL, NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('18', 'Task', '7', 'create', '1', NULL, '2025-01-02 03:04:13 UTC', '---
id:
-
- 7
user_id:
-
- 1
name:
- ''''
- Recreated standalone fixture task
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:13.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:13.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:13.000000000 Z
', NULL, NULL, NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('19', 'Task', '8', 'create', '1', NULL, '2025-01-02 03:04:13 UTC', '---
id:
-
- 8
user_id:
-
- 1
name:
- ''''
- Completed fixture task
asset_type:
-
- Contact
asset_id:
-
- 1
completed_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: 2025-01-02 03:04:13.000000000 Z
  zone: &1 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:13.000000000 Z
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &2 2025-01-02 03:04:13.000000000 Z
  zone: *1
  time: 2025-01-02 03:04:13.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *2
  zone: *1
  time: 2025-01-02 03:04:13.000000000 Z
', '1', 'Contact', NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('20', 'Comment', '1', 'create', '1', NULL, '2025-01-02 03:04:14 UTC', '---
id:
-
- 1
user_id:
-
- 1
commentable_type:
-
- Account
commentable_id:
-
- 1
comment:
-
- Fixture comment
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:14.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:14.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:14.000000000 Z
', '1', 'Account', NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('21', 'Comment', '2', 'create', '1', NULL, '2025-01-02 03:04:15 UTC', '---
id:
-
- 2
user_id:
-
- 1
commentable_type:
-
- Campaign
commentable_id:
-
- 1
comment:
-
- Fixture comment
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:15.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:15.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:15.000000000 Z
', '1', 'Campaign', NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('22', 'Comment', '3', 'create', '1', NULL, '2025-01-02 03:04:16 UTC', '---
id:
-
- 3
user_id:
-
- 1
commentable_type:
-
- Contact
commentable_id:
-
- 1
comment:
-
- Fixture comment
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:16.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:16.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:16.000000000 Z
', '1', 'Contact', NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('23', 'Comment', '4', 'create', '1', NULL, '2025-01-02 03:04:17 UTC', '---
id:
-
- 4
user_id:
-
- 1
commentable_type:
-
- Lead
commentable_id:
-
- 1
comment:
-
- Fixture comment
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:17.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:17.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:17.000000000 Z
', '1', 'Lead', NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('24', 'Comment', '5', 'create', '1', NULL, '2025-01-02 03:04:18 UTC', '---
id:
-
- 5
user_id:
-
- 1
commentable_type:
-
- Opportunity
commentable_id:
-
- 1
comment:
-
- Fixture comment
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:18.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:18.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:18.000000000 Z
', '1', 'Opportunity', NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('25', 'Comment', '6', 'create', '1', NULL, '2025-01-02 03:04:19 UTC', '---
id:
-
- 6
user_id:
-
- 1
commentable_type:
-
- Task
commentable_id:
-
- 1
comment:
-
- Fixture comment
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:19.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:19.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:19.000000000 Z
', '1', 'Task', NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('26', 'Email', '1', 'create', '1', NULL, '2025-01-02 03:04:20 UTC', '---
id:
-
- 1
imap_message_id:
-
- fixture-account@example.test
user_id:
-
- 1
mediator_type:
-
- Account
mediator_id:
-
- 1
sent_from:
-
- owner@example.test
sent_to:
-
- assignee@example.test
subject:
-
- Fixture email
body:
-
- Rails-created email
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:20.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:20.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:20.000000000 Z
', '1', 'Account', NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('27', 'Email', '2', 'create', '1', NULL, '2025-01-02 03:04:21 UTC', '---
id:
-
- 2
imap_message_id:
-
- fixture-contact@example.test
user_id:
-
- 1
mediator_type:
-
- Contact
mediator_id:
-
- 1
sent_from:
-
- owner@example.test
sent_to:
-
- assignee@example.test
subject:
-
- Fixture email
body:
-
- Rails-created email
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:21.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:21.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:21.000000000 Z
', '1', 'Contact', NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('28', 'Email', '3', 'create', '1', NULL, '2025-01-02 03:04:22 UTC', '---
id:
-
- 3
imap_message_id:
-
- fixture-lead@example.test
user_id:
-
- 1
mediator_type:
-
- Lead
mediator_id:
-
- 1
sent_from:
-
- owner@example.test
sent_to:
-
- assignee@example.test
subject:
-
- Fixture email
body:
-
- Rails-created email
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:22.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:22.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:22.000000000 Z
', '1', 'Lead', NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('29', 'Address', '1', 'create', '1', NULL, '2025-01-02 03:04:23 UTC', '---
id:
-
- 1
street1:
-
- 1 Fixture Street
city:
-
- Fixture City
state:
-
- CA
zipcode:
-
- ''90210''
country:
-
- US
address_type:
-
- Business
addressable_type:
-
- Account
addressable_id:
-
- 1
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:23.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:23.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:23.000000000 Z
', '1', 'Account', NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('30', 'Address', '2', 'create', '1', NULL, '2025-01-02 03:04:24 UTC', '---
id:
-
- 2
street1:
-
- 1 Fixture Street
city:
-
- Fixture City
state:
-
- CA
zipcode:
-
- ''90210''
country:
-
- US
address_type:
-
- Billing
addressable_type:
-
- Account
addressable_id:
-
- 1
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:24.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:24.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:24.000000000 Z
', '1', 'Account', NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('31', 'Address', '3', 'create', '1', NULL, '2025-01-02 03:04:25 UTC', '---
id:
-
- 3
street1:
-
- 1 Fixture Street
city:
-
- Fixture City
state:
-
- CA
zipcode:
-
- ''90210''
country:
-
- US
address_type:
-
- Shipping
addressable_type:
-
- Account
addressable_id:
-
- 1
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:25.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:25.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:25.000000000 Z
', '1', 'Account', NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('32', 'Address', '4', 'create', '1', NULL, '2025-01-02 03:04:26 UTC', '---
id:
-
- 4
street1:
-
- 1 Fixture Street
city:
-
- Fixture City
state:
-
- CA
zipcode:
-
- ''90210''
country:
-
- US
address_type:
-
- Business
addressable_type:
-
- Contact
addressable_id:
-
- 1
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:26.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:26.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:26.000000000 Z
', '1', 'Contact', NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('33', 'Address', '5', 'create', '1', NULL, '2025-01-02 03:04:27 UTC', '---
id:
-
- 5
street1:
-
- 1 Fixture Street
city:
-
- Fixture City
state:
-
- CA
zipcode:
-
- ''90210''
country:
-
- US
address_type:
-
- Billing
addressable_type:
-
- Contact
addressable_id:
-
- 1
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:27.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:27.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:27.000000000 Z
', '1', 'Contact', NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('34', 'Address', '6', 'create', '1', NULL, '2025-01-02 03:04:28 UTC', '---
id:
-
- 6
street1:
-
- 1 Fixture Street
city:
-
- Fixture City
state:
-
- CA
zipcode:
-
- ''90210''
country:
-
- US
address_type:
-
- Shipping
addressable_type:
-
- Contact
addressable_id:
-
- 1
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:28.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:28.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:28.000000000 Z
', '1', 'Contact', NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('35', 'Address', '7', 'create', '1', NULL, '2025-01-02 03:04:29 UTC', '---
id:
-
- 7
street1:
-
- 1 Fixture Street
city:
-
- Fixture City
state:
-
- CA
zipcode:
-
- ''90210''
country:
-
- US
address_type:
-
- Business
addressable_type:
-
- Lead
addressable_id:
-
- 1
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:29.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:29.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:29.000000000 Z
', '1', 'Lead', NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('36', 'Address', '8', 'create', '1', NULL, '2025-01-02 03:04:30 UTC', '---
id:
-
- 8
street1:
-
- 1 Fixture Street
city:
-
- Fixture City
state:
-
- CA
zipcode:
-
- ''90210''
country:
-
- US
address_type:
-
- Billing
addressable_type:
-
- Lead
addressable_id:
-
- 1
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:30.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:30.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:30.000000000 Z
', '1', 'Lead', NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('37', 'Address', '9', 'create', '1', NULL, '2025-01-02 03:04:31 UTC', '---
id:
-
- 9
street1:
-
- 1 Fixture Street
city:
-
- Fixture City
state:
-
- CA
zipcode:
-
- ''90210''
country:
-
- US
address_type:
-
- Shipping
addressable_type:
-
- Lead
addressable_id:
-
- 1
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:31.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:31.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:31.000000000 Z
', '1', 'Lead', NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('38', 'Account', '1', 'update', '1', '---
id: 1
user_id: 1
assigned_to: 2
name: Entity Fixture Account
access: Shared
website:
toll_free_phone:
phone:
fax:
deleted_at:
created_at: !ruby/object:ActiveSupport::TimeWithZone
  utc: 2025-01-02 03:04:08.000000000 Z
  zone: &1 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:08.000000000 Z
updated_at: !ruby/object:ActiveSupport::TimeWithZone
  utc: 2025-01-02 03:04:14.000000000 Z
  zone: *1
  time: 2025-01-02 03:04:14.000000000 Z
email:
background_info:
rating: 0
category:
subscribed_users: |
  ---
  - 2
  - 1
  - 1
contacts_count: 1
opportunities_count: 1
wikidata_id:
latitude:
longitude:
blog:
linkedin:
facebook:
twitter:
bluesky:
instagram:
mastodon:
tag_list: !ruby/array:ActsAsTaggableOn::TagList
  internal:
  - entity-fixture
  - domain-model
  ivars:
    :@parser: !ruby/class ''ActsAsTaggableOn::DefaultParser''
', '2025-01-02 03:04:31 UTC', '---
updated_at:
- !ruby/object:ActiveSupport::TimeWithZone
  utc: 2025-01-02 03:04:14.000000000 Z
  zone: &1 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:14.000000000 Z
- !ruby/object:ActiveSupport::TimeWithZone
  utc: 2025-01-02 03:04:31.000000000 Z
  zone: *1
  time: 2025-01-02 03:04:31.000000000 Z
tag_list:
- []
- - entity-fixture
  - domain-model
', NULL, NULL, NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('39', 'Account', '2', 'create', '1', NULL, '2025-01-02 03:04:31 UTC', '---
id:
-
- 2
user_id:
-
- 1
name:
- ''''
- Empty subscribers fixture
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:31.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:31.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:31.000000000 Z
', NULL, NULL, NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('40', 'Account', '3', 'create', '1', NULL, '2025-01-02 03:04:31 UTC', '---
id:
-
- 3
user_id:
-
- 1
name:
- ''''
- Legacy empty subscribers fixture
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2025-01-02 03:04:31.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:31.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2025-01-02 03:04:31.000000000 Z
', NULL, NULL, NULL);
INSERT INTO public."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "object_changes", "related_id", "related_type", "transaction_id") VALUES ('41', 'Account', '1', 'update', '1', '---
id: 1
user_id: 1
assigned_to: 2
name: Entity Fixture Account
access: Shared
website:
toll_free_phone:
phone:
fax:
deleted_at: !ruby/object:ActiveSupport::TimeWithZone
  utc: 2025-01-02 03:04:31.000000000 Z
  zone: &1 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2025-01-02 03:04:31.000000000 Z
created_at: !ruby/object:ActiveSupport::TimeWithZone
  utc: 2025-01-02 03:04:08.000000000 Z
  zone: *1
  time: 2025-01-02 03:04:08.000000000 Z
updated_at: !ruby/object:ActiveSupport::TimeWithZone
  utc: 2025-01-02 03:04:31.000000000 Z
  zone: *1
  time: 2025-01-02 03:04:31.000000000 Z
email:
background_info:
rating: 0
category:
subscribed_users: |
  ---
  - 2
  - 1
  - 1
contacts_count: 1
opportunities_count: 1
wikidata_id:
latitude:
longitude:
blog:
linkedin:
facebook:
twitter:
bluesky:
instagram:
mastodon:
tag_list: !ruby/array:ActsAsTaggableOn::TagList
  internal:
  - entity-fixture
  - domain-model
  ivars:
    :@parser: !ruby/class ''ActsAsTaggableOn::DefaultParser''
', '2025-01-02 03:04:31 UTC', '---
background_info:
-
- Versioned fixture update
', NULL, NULL, NULL);
SELECT pg_catalog.setval('public.versions_id_seq', 41, true);
