-- Generated by spring/scripts/generate-seed-fixture.sh from lib/tasks/ffcrm/seed_fixture.rake.
-- Rails-written rows for every application table; loaded on top of rails_schema.sql by the Spring
-- data-fidelity tests. Regenerate (do not hand-edit) when the seed task or the Rails schema changes.
--
-- PostgreSQL database dump
--



SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: account_contacts; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.account_contacts (id, account_id, contact_id, deleted_at, created_at, updated_at) VALUES (1, 1, 1, NULL, '2026-10-07 12:00:00', '2026-10-07 12:00:00');
INSERT INTO public.account_contacts (id, account_id, contact_id, deleted_at, created_at, updated_at) VALUES (2, 2, 2, NULL, '2026-10-07 12:00:00', '2026-10-07 12:00:00');
INSERT INTO public.account_contacts (id, account_id, contact_id, deleted_at, created_at, updated_at) VALUES (3, 2, 1, '2026-09-17 12:00:00', '2026-10-07 12:00:00', '2026-10-07 12:00:00');


--
-- Data for Name: account_opportunities; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.account_opportunities (id, account_id, opportunity_id, deleted_at, created_at, updated_at) VALUES (1, 1, 1, NULL, '2026-10-07 12:00:00', '2026-10-07 12:00:00');
INSERT INTO public.account_opportunities (id, account_id, opportunity_id, deleted_at, created_at, updated_at) VALUES (2, 2, 2, NULL, '2026-10-07 12:00:00', '2026-10-07 12:00:00');
INSERT INTO public.account_opportunities (id, account_id, opportunity_id, deleted_at, created_at, updated_at) VALUES (3, 1, 2, '2026-10-03 12:00:00', '2026-10-07 12:00:00', '2026-10-07 12:00:00');


--
-- Data for Name: accounts; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.accounts (id, user_id, assigned_to, name, access, website, toll_free_phone, phone, fax, deleted_at, created_at, updated_at, email, background_info, rating, category, subscribed_users, contacts_count, opportunities_count, wikidata_id, latitude, longitude, blog, linkedin, facebook, twitter, bluesky, instagram, mastodon) VALUES (3, 1, NULL, 'Ünïcødé & Sons', 'Shared', NULL, NULL, NULL, NULL, NULL, '2026-10-07 12:00:00', '2026-10-07 12:00:00', NULL, NULL, 2, 'partner', NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts (id, user_id, assigned_to, name, access, website, toll_free_phone, phone, fax, deleted_at, created_at, updated_at, email, background_info, rating, category, subscribed_users, contacts_count, opportunities_count, wikidata_id, latitude, longitude, blog, linkedin, facebook, twitter, bluesky, instagram, mastodon) VALUES (4, 1, NULL, 'Initech', 'Public', NULL, NULL, NULL, NULL, '2026-10-02 12:00:00', '2026-10-07 12:00:00', '2026-10-07 12:00:00', NULL, NULL, 1, NULL, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts (id, user_id, assigned_to, name, access, website, toll_free_phone, phone, fax, deleted_at, created_at, updated_at, email, background_info, rating, category, subscribed_users, contacts_count, opportunities_count, wikidata_id, latitude, longitude, blog, linkedin, facebook, twitter, bluesky, instagram, mastodon) VALUES (2, 2, NULL, 'Globex', 'Private', NULL, NULL, NULL, NULL, NULL, '2026-10-07 12:00:00', '2026-10-07 12:00:00', NULL, NULL, 0, NULL, NULL, 2, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.accounts (id, user_id, assigned_to, name, access, website, toll_free_phone, phone, fax, deleted_at, created_at, updated_at, email, background_info, rating, category, subscribed_users, contacts_count, opportunities_count, wikidata_id, latitude, longitude, blog, linkedin, facebook, twitter, bluesky, instagram, mastodon) VALUES (1, 1, 2, 'Acme Corp', 'Public', 'https://acme.example', '1-800-555-0199', '+1 555 0200', '+1 555 0198', NULL, '2026-10-07 12:00:00', '2026-10-07 12:00:00', 'info@acme.example', 'Key account.
Second line with ünïcödé.', 5, 'customer', '---
- 1
- 2
- 2
- 1
', 1, 2, 'Q42', 37.774929, -122.419418, 'https://acme.example/blog', 'company/acme', 'acme', 'acme', 'acme.bsky.social', 'acme', '@acme@example.social');


--
-- Data for Name: activities; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.activities (id, user_id, subject_type, subject_id, action, info, private, created_at, updated_at) VALUES (1, 1, 'Account', 1, 'viewed', 'Legacy activity row', false, '2024-01-02 03:04:05', '2024-01-02 03:04:05');
INSERT INTO public.activities (id, user_id, subject_type, subject_id, action, info, private, created_at, updated_at) VALUES (2, 2, 'Contact', 1, 'updated', '', true, '2024-02-03 04:05:06', '2024-02-03 04:05:06');


--
-- Data for Name: addresses; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.addresses (id, street1, street2, city, state, zipcode, country, full_address, address_type, addressable_type, addressable_id, created_at, updated_at, deleted_at) VALUES (1, '1 Market St', 'Suite 100', 'San Francisco', 'CA', '94105', 'US', NULL, 'Business', 'Account', 1, '2026-10-07 12:00:00', '2026-10-07 12:00:00', NULL);
INSERT INTO public.addresses (id, street1, street2, city, state, zipcode, country, full_address, address_type, addressable_type, addressable_id, created_at, updated_at, deleted_at) VALUES (2, NULL, NULL, NULL, NULL, NULL, NULL, 'Postfach 1, 10115 Berlin, DE', 'Billing', 'Contact', 1, '2026-10-07 12:00:00', '2026-10-07 12:00:00', NULL);
INSERT INTO public.addresses (id, street1, street2, city, state, zipcode, country, full_address, address_type, addressable_type, addressable_id, created_at, updated_at, deleted_at) VALUES (3, NULL, NULL, 'Hamburg', NULL, NULL, 'DE', NULL, 'Shipping', 'Lead', 1, '2026-10-07 12:00:00', '2026-10-07 12:00:00', NULL);
INSERT INTO public.addresses (id, street1, street2, city, state, zipcode, country, full_address, address_type, addressable_type, addressable_id, created_at, updated_at, deleted_at) VALUES (4, NULL, NULL, 'Old', NULL, NULL, NULL, NULL, 'Shipping', 'Account', 1, '2026-10-07 12:00:00', '2026-10-07 12:00:00', '2026-09-28 12:00:00');


--
-- Data for Name: avatars; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.avatars (id, user_id, entity_type, entity_id, image_file_size, image_file_name, image_content_type, created_at, updated_at) VALUES (1, 1, 'User', 1, 12345, 'alice.png', 'image/png', '2026-10-07 12:00:00', '2026-10-07 12:00:00');
INSERT INTO public.avatars (id, user_id, entity_type, entity_id, image_file_size, image_file_name, image_content_type, created_at, updated_at) VALUES (2, 2, 'Contact', 1, 54321, 'carla.jpg', 'image/jpeg', '2026-10-07 12:00:00', '2026-10-07 12:00:00');


--
-- Data for Name: campaigns; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.campaigns (id, user_id, assigned_to, name, access, status, budget, target_leads, target_conversion, target_revenue, leads_count, opportunities_count, revenue, starts_on, ends_on, objectives, deleted_at, created_at, updated_at, background_info, subscribed_users) VALUES (2, 2, NULL, 'Retired Campaign', 'Private', 'completed', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-09-27 12:00:00', '2026-10-07 12:00:00', '2026-10-07 12:00:00', NULL, NULL);
INSERT INTO public.campaigns (id, user_id, assigned_to, name, access, status, budget, target_leads, target_conversion, target_revenue, leads_count, opportunities_count, revenue, starts_on, ends_on, objectives, deleted_at, created_at, updated_at, background_info, subscribed_users) VALUES (1, 1, 2, 'Autumn Launch', 'Public', 'started', 25000.50, 120, 12.5, 250000.00, 2, 1, 1250.25, '2026-09-01', '2026-12-31', 'Line one
Line two', NULL, '2026-10-07 12:00:00', '2026-10-07 12:00:00', 'Campaign background', '---
- 1
');


--
-- Data for Name: comments; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.comments (id, user_id, commentable_type, commentable_id, private, title, comment, created_at, updated_at, state) VALUES (1, 1, 'Account', 1, false, 'Review', 'Quarterly review scheduled with @bob.', '2026-10-07 12:00:00', '2026-10-07 12:00:00', 'Expanded');
INSERT INTO public.comments (id, user_id, commentable_type, commentable_id, private, title, comment, created_at, updated_at, state) VALUES (2, 2, 'Contact', 1, true, '', 'Prefers morning calls.', '2026-10-07 12:00:00', '2026-10-07 12:00:00', 'Collapsed');
INSERT INTO public.comments (id, user_id, commentable_type, commentable_id, private, title, comment, created_at, updated_at, state) VALUES (3, 2, 'Task', 1, NULL, '', 'On it.', '2026-10-07 12:00:00', '2026-10-07 12:00:00', 'Expanded');


--
-- Data for Name: contact_opportunities; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.contact_opportunities (id, contact_id, opportunity_id, role, deleted_at, created_at, updated_at) VALUES (1, 1, 1, 'Decision maker', NULL, '2026-10-07 12:00:00', '2026-10-07 12:00:00');
INSERT INTO public.contact_opportunities (id, contact_id, opportunity_id, role, deleted_at, created_at, updated_at) VALUES (2, 2, 1, 'Influencer', NULL, '2026-10-07 12:00:00', '2026-10-07 12:00:00');
INSERT INTO public.contact_opportunities (id, contact_id, opportunity_id, role, deleted_at, created_at, updated_at) VALUES (3, 2, 2, NULL, NULL, '2026-10-07 12:00:00', '2026-10-07 12:00:00');
INSERT INTO public.contact_opportunities (id, contact_id, opportunity_id, role, deleted_at, created_at, updated_at) VALUES (4, 1, 2, NULL, '2026-10-03 12:00:00', '2026-10-07 12:00:00', '2026-10-07 12:00:00');


--
-- Data for Name: contacts; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.contacts (id, user_id, lead_id, assigned_to, reports_to, first_name, last_name, access, title, department, source, email, alt_email, phone, mobile, fax, blog, linkedin, facebook, twitter, born_on, do_not_call, deleted_at, created_at, updated_at, background_info, subscribed_users, zoom, teams, signal, instagram, mastodon, bluesky) VALUES (2, 2, 2, NULL, 1, 'Carl', 'Converted', 'Private', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true, NULL, '2026-10-07 12:00:00', '2026-10-07 12:00:00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.contacts (id, user_id, lead_id, assigned_to, reports_to, first_name, last_name, access, title, department, source, email, alt_email, phone, mobile, fax, blog, linkedin, facebook, twitter, born_on, do_not_call, deleted_at, created_at, updated_at, background_info, subscribed_users, zoom, teams, signal, instagram, mastodon, bluesky) VALUES (3, 2, NULL, NULL, NULL, 'Former', 'Contact', 'Public', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, '2026-10-05 12:00:00', '2026-10-07 12:00:00', '2026-10-07 12:00:00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.contacts (id, user_id, lead_id, assigned_to, reports_to, first_name, last_name, access, title, department, source, email, alt_email, phone, mobile, fax, blog, linkedin, facebook, twitter, born_on, do_not_call, deleted_at, created_at, updated_at, background_info, subscribed_users, zoom, teams, signal, instagram, mastodon, bluesky) VALUES (1, 1, NULL, 2, NULL, 'Carla', 'Chief', 'Public', 'CEO', 'Executive', 'referral', 'carla@acme.example', 'carla.alt@acme.example', '+1 555 0110', '+1 555 0111', '+1 555 0112', 'https://carla.example', 'in/carla', 'carla', 'carla', '1975-02-28', false, NULL, '2026-10-07 12:00:00', '2026-10-07 12:00:00', 'Decision maker', '---
- 1
- 2
- 2
', 'carla-zoom', 'carla-teams', '+15550111', 'carla', '@carla@example.social', 'carla.bsky.social');


--
-- Data for Name: emails; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.emails (id, imap_message_id, user_id, mediator_type, mediator_id, sent_from, sent_to, cc, bcc, subject, body, header, sent_at, received_at, deleted_at, created_at, updated_at, state) VALUES (1, '<msg-1@example.com>', 1, 'Account', 1, 'alice@example.com', 'info@acme.example', 'bob@example.com', 'archive@example.com', 'Renewal terms', 'Hi,

Please find the terms attached.
', 'X-Mailer: Fixture
X-Priority: 1', '2026-10-07 10:00:00', '2026-10-07 11:00:00', NULL, '2026-10-07 12:00:00', '2026-10-07 12:00:00', 'Expanded');
INSERT INTO public.emails (id, imap_message_id, user_id, mediator_type, mediator_id, sent_from, sent_to, cc, bcc, subject, body, header, sent_at, received_at, deleted_at, created_at, updated_at, state) VALUES (2, '<msg-2@example.com>', 2, 'Contact', 1, 'bob@example.com', 'carla@acme.example', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-10-07 12:00:00', '2026-10-07 12:00:00', 'Collapsed');
INSERT INTO public.emails (id, imap_message_id, user_id, mediator_type, mediator_id, sent_from, sent_to, cc, bcc, subject, body, header, sent_at, received_at, deleted_at, created_at, updated_at, state) VALUES (3, '<msg-3@example.com>', NULL, NULL, NULL, 'nobody@example.com', 'x@example.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-10-06 12:00:00', '2026-10-07 12:00:00', '2026-10-07 12:00:00', 'Expanded');


--
-- Data for Name: field_groups; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.field_groups (id, name, label, "position", hint, created_at, updated_at, tag_id, klass_name) VALUES (1, 'vip_details', 'VIP details', 2, 'Shown for VIP contacts', '2026-10-07 12:00:00', '2026-10-07 12:00:00', 1, 'Contact');
INSERT INTO public.field_groups (id, name, label, "position", hint, created_at, updated_at, tag_id, klass_name) VALUES (2, 'default', 'Account details', 1, NULL, '2026-10-07 12:00:00', '2026-10-07 12:00:00', NULL, 'Account');


--
-- Data for Name: fields; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.fields (id, type, field_group_id, "position", name, label, hint, placeholder, "as", collection, disabled, required, maxlength, created_at, updated_at, pair_id, settings, minlength, pattern, autofocus, autocomplete, list, multiple, title) VALUES (1, 'CoreField', 2, 2, 'email', 'Email', 'Primary email', 'name@example.com', 'email', NULL, NULL, true, 254, '2026-10-07 12:00:00', '2026-10-07 12:00:00', NULL, NULL, 3, '.+@.+', 'autofocus', 'email', NULL, NULL, 'Email address');
INSERT INTO public.fields (id, type, field_group_id, "position", name, label, hint, placeholder, "as", collection, disabled, required, maxlength, created_at, updated_at, pair_id, settings, minlength, pattern, autofocus, autocomplete, list, multiple, title) VALUES (2, 'CoreField', 1, 1, 'tier', 'Tier', NULL, NULL, 'select', '---
- gold
- silver
- bronze
', false, NULL, NULL, '2026-10-07 12:00:00', '2026-10-07 12:00:00', 1, '--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
allow_blank: true
', 0, NULL, NULL, NULL, 'tiers', 'multiple', NULL);


--
-- Data for Name: groups; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.groups (id, name, created_at, updated_at) VALUES (1, 'Sales', '2026-10-07 12:00:00', '2026-10-07 12:00:00');
INSERT INTO public.groups (id, name, created_at, updated_at) VALUES (2, 'Support', '2026-10-07 12:00:00', '2026-10-07 12:00:00');


--
-- Data for Name: groups_users; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.groups_users (group_id, user_id) VALUES (1, 1);
INSERT INTO public.groups_users (group_id, user_id) VALUES (1, 2);
INSERT INTO public.groups_users (group_id, user_id) VALUES (2, 3);


--
-- Data for Name: leads; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.leads (id, user_id, campaign_id, assigned_to, first_name, last_name, access, title, company, source, status, referred_by, email, alt_email, phone, mobile, blog, linkedin, facebook, twitter, rating, do_not_call, deleted_at, created_at, updated_at, background_info, subscribed_users, zoom, teams, signal, instagram, mastodon, bluesky) VALUES (1, 1, 1, 2, 'Lena', 'Lead', 'Public', 'CTO', 'Leadify', 'web', 'contacted', 'Bob', 'lena@leadify.example', 'lena.alt@leadify.example', '+49 30 1234', '+49 170 1234', 'https://leadify.example', 'in/lena', 'lena', 'lena', 3, true, NULL, '2026-10-07 12:00:00', '2026-10-07 12:00:00', 'Met at conference', '---
- 1
', 'lena-zoom', 'lena-teams', '+491701234', 'lena', '@lena@example.social', 'lena.bsky.social');
INSERT INTO public.leads (id, user_id, campaign_id, assigned_to, first_name, last_name, access, title, company, source, status, referred_by, email, alt_email, phone, mobile, blog, linkedin, facebook, twitter, rating, do_not_call, deleted_at, created_at, updated_at, background_info, subscribed_users, zoom, teams, signal, instagram, mastodon, bluesky) VALUES (2, 2, 1, NULL, 'Carl', 'Converted', 'Public', NULL, NULL, NULL, 'converted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, false, NULL, '2026-10-07 12:00:00', '2026-10-07 12:00:00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.leads (id, user_id, campaign_id, assigned_to, first_name, last_name, access, title, company, source, status, referred_by, email, alt_email, phone, mobile, blog, linkedin, facebook, twitter, rating, do_not_call, deleted_at, created_at, updated_at, background_info, subscribed_users, zoom, teams, signal, instagram, mastodon, bluesky) VALUES (3, 2, NULL, NULL, 'Gone', 'Lead', 'Public', NULL, NULL, NULL, 'rejected', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, false, '2026-10-06 12:00:00', '2026-10-07 12:00:00', '2026-10-07 12:00:00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);


--
-- Data for Name: lists; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.lists (id, name, url, created_at, updated_at, user_id) VALUES (1, 'My hot leads', '/leads?q[status_eq]=contacted&sort=created_at+desc', '2026-10-07 12:00:00', '2026-10-07 12:00:00', 1);
INSERT INTO public.lists (id, name, url, created_at, updated_at, user_id) VALUES (2, 'All accounts', '/accounts', '2026-10-07 12:00:00', '2026-10-07 12:00:00', NULL);


--
-- Data for Name: opportunities; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.opportunities (id, user_id, campaign_id, assigned_to, name, access, source, stage, probability, amount, discount, closes_on, deleted_at, created_at, updated_at, background_info, subscribed_users) VALUES (1, 1, 1, 2, 'Acme renewal', 'Public', 'campaign', 'proposal', 60, 1234567.89, 1000.10, '2026-11-30', NULL, '2026-10-07 12:00:00', '2026-10-07 12:00:00', 'Renewal', '---
- 2
');
INSERT INTO public.opportunities (id, user_id, campaign_id, assigned_to, name, access, source, stage, probability, amount, discount, closes_on, deleted_at, created_at, updated_at, background_info, subscribed_users) VALUES (2, 2, NULL, NULL, 'Globex pilot', 'Shared', NULL, 'prospecting', 10, 500.00, NULL, NULL, NULL, '2026-10-07 12:00:00', '2026-10-07 12:00:00', NULL, NULL);
INSERT INTO public.opportunities (id, user_id, campaign_id, assigned_to, name, access, source, stage, probability, amount, discount, closes_on, deleted_at, created_at, updated_at, background_info, subscribed_users) VALUES (3, 2, NULL, NULL, 'Lost deal', 'Public', NULL, 'lost', NULL, NULL, NULL, NULL, '2026-10-04 12:00:00', '2026-10-07 12:00:00', '2026-10-07 12:00:00', NULL, NULL);


--
-- Data for Name: permissions; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.permissions (id, user_id, asset_type, asset_id, created_at, updated_at, group_id) VALUES (1, 3, 'Account', 3, '2026-10-07 12:00:00', '2026-10-07 12:00:00', NULL);
INSERT INTO public.permissions (id, user_id, asset_type, asset_id, created_at, updated_at, group_id) VALUES (2, NULL, 'Account', 3, '2026-10-07 12:00:00', '2026-10-07 12:00:00', 2);
INSERT INTO public.permissions (id, user_id, asset_type, asset_id, created_at, updated_at, group_id) VALUES (3, 1, 'Opportunity', 2, '2026-10-07 12:00:00', '2026-10-07 12:00:00', NULL);


--
-- Data for Name: preferences; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.preferences (id, user_id, name, value, created_at, updated_at) VALUES (1, 1, 'locale', 'ImVuLVVTIg==
', '2026-10-07 12:00:00', '2026-10-07 12:00:00');
INSERT INTO public.preferences (id, user_id, name, value, created_at, updated_at) VALUES (2, 1, 'activity_asset', 'WyJhY2NvdW50cyIsImNvbnRhY3RzIl0=
', '2026-10-07 12:00:00', '2026-10-07 12:00:00');
INSERT INTO public.preferences (id, user_id, name, value, created_at, updated_at) VALUES (3, 2, 'contacts_per_page', 'NTA=
', '2026-10-07 12:00:00', '2026-10-07 12:00:00');
INSERT INTO public.preferences (id, user_id, name, value, created_at, updated_at) VALUES (4, NULL, 'shared', 'eyJ0aGVtZSI6ImxpZ2h0In0=
', '2026-10-07 12:00:00', '2026-10-07 12:00:00');


--
-- Data for Name: research_tools; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.research_tools (id, name, url_template, enabled, created_at, updated_at) VALUES (1, 'Wikipedia', 'https://en.wikipedia.org/wiki/{{name}}', true, '2026-10-07 12:00:00', '2026-10-07 12:00:00');
INSERT INTO public.research_tools (id, name, url_template, enabled, created_at, updated_at) VALUES (2, 'Disabled tool', 'https://example.com/?q={{name}}', false, '2026-10-07 12:00:00', '2026-10-07 12:00:00');


--
-- Data for Name: settings; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.settings (id, name, value, created_at, updated_at) VALUES (1, 'company_name', '--- Fixture Co
', '2026-10-07 12:00:00', '2026-10-07 12:00:00');
INSERT INTO public.settings (id, name, value, created_at, updated_at) VALUES (2, 'require_unique_account_names', '--- false
', '2026-10-07 12:00:00', '2026-10-07 12:00:00');
INSERT INTO public.settings (id, name, value, created_at, updated_at) VALUES (3, 'locale_options', '---
- en-US
- de
', '2026-10-07 12:00:00', '2026-10-07 12:00:00');
INSERT INTO public.settings (id, name, value, created_at, updated_at) VALUES (4, 'email_dropbox', '---
server: imap.example.com
port: 993
ssl: true
', '2026-10-07 12:00:00', '2026-10-07 12:00:00');


--
-- Data for Name: taggings; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.taggings (id, tag_id, taggable_id, tagger_id, tagger_type, taggable_type, context, created_at) VALUES (1, 1, 1, NULL, NULL, 'Account', 'tags', '2026-10-07 12:00:00');
INSERT INTO public.taggings (id, tag_id, taggable_id, tagger_id, tagger_type, taggable_type, context, created_at) VALUES (2, 2, 1, NULL, NULL, 'Account', 'tags', '2026-10-07 12:00:00');
INSERT INTO public.taggings (id, tag_id, taggable_id, tagger_id, tagger_type, taggable_type, context, created_at) VALUES (3, 1, 1, NULL, NULL, 'Contact', 'tags', '2026-10-07 12:00:00');
INSERT INTO public.taggings (id, tag_id, taggable_id, tagger_id, tagger_type, taggable_type, context, created_at) VALUES (4, 3, 1, 1, 'User', 'Lead', 'tags', '2026-10-07 12:00:00');


--
-- Data for Name: tags; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.tags (id, name, taggings_count) VALUES (2, 'enterprise', 1);
INSERT INTO public.tags (id, name, taggings_count) VALUES (1, 'vip', 2);
INSERT INTO public.tags (id, name, taggings_count) VALUES (3, 'hot', 1);


--
-- Data for Name: tasks; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.tasks (id, user_id, assigned_to, completed_by, name, asset_type, asset_id, priority, category, bucket, due_at, completed_at, deleted_at, created_at, updated_at, background_info, subscribed_users) VALUES (2, 2, NULL, NULL, 'Email Carla', 'Contact', 1, NULL, 'email', 'due_this_week', '2026-10-11 23:59:59.999999', NULL, NULL, '2026-10-07 12:00:00', '2026-10-07 12:00:00', NULL, NULL);
INSERT INTO public.tasks (id, user_id, assigned_to, completed_by, name, asset_type, asset_id, priority, category, bucket, due_at, completed_at, deleted_at, created_at, updated_at, background_info, subscribed_users) VALUES (3, 1, NULL, NULL, 'Standalone task', NULL, NULL, NULL, NULL, 'due_asap', NULL, NULL, NULL, '2026-10-07 12:00:00', '2026-10-07 12:00:00', NULL, NULL);
INSERT INTO public.tasks (id, user_id, assigned_to, completed_by, name, asset_type, asset_id, priority, category, bucket, due_at, completed_at, deleted_at, created_at, updated_at, background_info, subscribed_users) VALUES (4, 1, NULL, 1, 'Done task', 'Opportunity', 1, NULL, NULL, 'due_asap', NULL, '2026-10-06 12:00:00', NULL, '2026-10-07 12:00:00', '2026-10-07 12:00:00', NULL, NULL);
INSERT INTO public.tasks (id, user_id, assigned_to, completed_by, name, asset_type, asset_id, priority, category, bucket, due_at, completed_at, deleted_at, created_at, updated_at, background_info, subscribed_users) VALUES (5, 2, NULL, NULL, 'Deleted task', NULL, NULL, NULL, NULL, 'due_asap', NULL, NULL, '2026-10-07 11:00:00', '2026-10-07 12:00:00', '2026-10-07 12:00:00', NULL, NULL);
INSERT INTO public.tasks (id, user_id, assigned_to, completed_by, name, asset_type, asset_id, priority, category, bucket, due_at, completed_at, deleted_at, created_at, updated_at, background_info, subscribed_users) VALUES (1, 1, 2, NULL, 'Call Acme', 'Account', 1, 'high', 'call', 'due_tomorrow', '2026-10-08 00:00:00', NULL, NULL, '2026-10-07 12:00:00', '2026-10-07 12:00:00', 'Discuss renewal', '---
- 1
- 2
- 2
');


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.users (id, username, email, first_name, last_name, title, company, alt_email, phone, mobile, google, encrypted_password, password_salt, last_sign_in_at, current_sign_in_at, last_sign_in_ip, current_sign_in_ip, sign_in_count, deleted_at, created_at, updated_at, admin, suspended_at, unconfirmed_email, reset_password_token, reset_password_sent_at, remember_token, remember_created_at, authentication_token, confirmation_token, confirmed_at, confirmation_sent_at, subscribe_to_comment_replies, receive_assigned_notifications, zoom, teams, signal, instagram, facebook, mastodon, bluesky, twitter, linkedin, blog) VALUES (2, 'bob', 'bob@example.com', 'Bob', 'Builder', NULL, NULL, NULL, NULL, NULL, NULL, 'b5db349d2b7881d2443c70cdc2790f4a0ed2eeeb5725fe51fb69a31a7dd6ef936b44dc0b965efb655a93cc69ab9d409ab4d808551cc1ec6c5a47ba94d9a68b10', 'g_bwSJkomji9j4taUUu_', NULL, NULL, NULL, NULL, 0, NULL, '2026-10-07 12:00:00', '2026-10-07 12:00:00', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-10-07 12:00:00', NULL, false, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.users (id, username, email, first_name, last_name, title, company, alt_email, phone, mobile, google, encrypted_password, password_salt, last_sign_in_at, current_sign_in_at, last_sign_in_ip, current_sign_in_ip, sign_in_count, deleted_at, created_at, updated_at, admin, suspended_at, unconfirmed_email, reset_password_token, reset_password_sent_at, remember_token, remember_created_at, authentication_token, confirmation_token, confirmed_at, confirmation_sent_at, subscribe_to_comment_replies, receive_assigned_notifications, zoom, teams, signal, instagram, facebook, mastodon, bluesky, twitter, linkedin, blog) VALUES (3, 'carol', 'carol@example.com', 'Carol', 'Suspended', NULL, NULL, NULL, NULL, NULL, NULL, 'a66650c917c14061c7a74fa09a4eb491aba6cde1c116745fca3e7a7956a0e4b2523a260d4646067636f8e174f71636aee849eceaf09e2d7c9dfb2dc7c8587539', 'bBUxzzNLiV2qGKyNFgUZ', NULL, NULL, NULL, NULL, 0, NULL, '2026-10-07 12:00:00', '2026-10-07 12:00:00', false, '2026-10-06 12:00:00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-10-07 12:00:00', NULL, true, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.users (id, username, email, first_name, last_name, title, company, alt_email, phone, mobile, google, encrypted_password, password_salt, last_sign_in_at, current_sign_in_at, last_sign_in_ip, current_sign_in_ip, sign_in_count, deleted_at, created_at, updated_at, admin, suspended_at, unconfirmed_email, reset_password_token, reset_password_sent_at, remember_token, remember_created_at, authentication_token, confirmation_token, confirmed_at, confirmation_sent_at, subscribe_to_comment_replies, receive_assigned_notifications, zoom, teams, signal, instagram, facebook, mastodon, bluesky, twitter, linkedin, blog) VALUES (4, 'dave', 'dave@example.com', 'Dave', 'Deleted', NULL, NULL, NULL, NULL, NULL, NULL, 'cfb4ea3605835afdfe1f15c9f50807a4c9889a3773f13184691237b967be1144a0653e9f3086448709a0cd5552ca21f6010f6c9953d4ac6d1236827c5d40cbf6', 't7J1wy9wrkFyXD5xM5sX', NULL, NULL, NULL, NULL, 0, '2026-09-07 12:00:00', '2026-10-07 12:00:00', '2026-10-07 12:00:00', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-10-07 12:00:00', NULL, true, true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.users (id, username, email, first_name, last_name, title, company, alt_email, phone, mobile, google, encrypted_password, password_salt, last_sign_in_at, current_sign_in_at, last_sign_in_ip, current_sign_in_ip, sign_in_count, deleted_at, created_at, updated_at, admin, suspended_at, unconfirmed_email, reset_password_token, reset_password_sent_at, remember_token, remember_created_at, authentication_token, confirmation_token, confirmed_at, confirmation_sent_at, subscribe_to_comment_replies, receive_assigned_notifications, zoom, teams, signal, instagram, facebook, mastodon, bluesky, twitter, linkedin, blog) VALUES (1, 'alice', 'alice@example.com', 'Alice', 'Admin', 'Head of Sales', 'Fat Free CRM', 'alice.alt@example.com', '+1 555 0100', '+1 555 0101', 'alice.google', '9addb181e7658186ee563b077608b7b01d102b0b2e0f826d33da86b1de3db918d4fa4431d07f669054e1f1af81b4b374b8fe54780fe7e7759edd6a8429431411', 'AbtXhsHQzx16e3PXrYx-', '2026-10-05 12:00:00', '2026-10-07 11:00:00', '10.0.0.7', '10.0.0.8', 42, NULL, '2026-10-07 12:00:00', '2026-10-07 12:00:00', true, NULL, NULL, NULL, NULL, NULL, '2026-10-04 12:00:00', NULL, NULL, '2026-10-07 12:00:00', NULL, true, false, 'alice-zoom', 'alice-teams', '+15550101', 'alice', 'alice.fb', '@alice@example.social', 'alice.bsky.social', 'alice', 'in/alice', 'https://blog.example.com/alice');


--
-- Data for Name: versions; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (1, 'User', 1, 'create', NULL, NULL, '2026-10-07 12:00:00', '---
id:
-
- 1
username:
- ''''
- alice
email:
-
- alice@example.com
first_name:
-
- Alice
last_name:
-
- Admin
title:
-
- Head of Sales
company:
-
- Fat Free CRM
alt_email:
-
- alice.alt@example.com
phone:
-
- "+1 555 0100"
mobile:
-
- "+1 555 0101"
google:
-
- alice.google
encrypted_password:
- ''''
- 9addb181e7658186ee563b077608b7b01d102b0b2e0f826d33da86b1de3db918d4fa4431d07f669054e1f1af81b4b374b8fe54780fe7e7759edd6a8429431411
password_salt:
- ''''
- AbtXhsHQzx16e3PXrYx-
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2026-10-07 12:00:00.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-10-07 12:00:00.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2026-10-07 12:00:00.000000000 Z
admin:
- false
- true
confirmed_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: 2026-10-07 12:00:00.000000000 Z
  zone: *2
  time: 2026-10-07 12:00:00.000000000 Z
receive_assigned_notifications:
- true
- false
zoom:
-
- alice-zoom
teams:
-
- alice-teams
signal:
-
- "+15550101"
instagram:
-
- alice
facebook:
-
- alice.fb
mastodon:
-
- "@alice@example.social"
bluesky:
-
- alice.bsky.social
twitter:
-
- alice
linkedin:
-
- in/alice
blog:
-
- https://blog.example.com/alice
', NULL, NULL, NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (2, 'User', 2, 'create', NULL, NULL, '2026-10-07 12:00:00', '---
id:
-
- 2
username:
- ''''
- bob
email:
-
- bob@example.com
first_name:
-
- Bob
last_name:
-
- Builder
encrypted_password:
- ''''
- b5db349d2b7881d2443c70cdc2790f4a0ed2eeeb5725fe51fb69a31a7dd6ef936b44dc0b965efb655a93cc69ab9d409ab4d808551cc1ec6c5a47ba94d9a68b10
password_salt:
- ''''
- g_bwSJkomji9j4taUUu_
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2026-10-07 12:00:00.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-10-07 12:00:00.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2026-10-07 12:00:00.000000000 Z
confirmed_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: 2026-10-07 12:00:00.000000000 Z
  zone: *2
  time: 2026-10-07 12:00:00.000000000 Z
subscribe_to_comment_replies:
- true
- false
', NULL, NULL, NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (3, 'User', 3, 'create', NULL, NULL, '2026-10-07 12:00:00', '---
id:
-
- 3
username:
- ''''
- carol
email:
-
- carol@example.com
first_name:
-
- Carol
last_name:
-
- Suspended
encrypted_password:
- ''''
- a66650c917c14061c7a74fa09a4eb491aba6cde1c116745fca3e7a7956a0e4b2523a260d4646067636f8e174f71636aee849eceaf09e2d7c9dfb2dc7c8587539
password_salt:
- ''''
- bBUxzzNLiV2qGKyNFgUZ
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2026-10-07 12:00:00.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-10-07 12:00:00.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2026-10-07 12:00:00.000000000 Z
suspended_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: 2026-10-06 12:00:00.000000000 Z
  zone: *2
  time: 2026-10-06 12:00:00.000000000 Z
confirmed_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: 2026-10-07 12:00:00.000000000 Z
  zone: *2
  time: 2026-10-07 12:00:00.000000000 Z
', NULL, NULL, NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (4, 'User', 4, 'create', NULL, NULL, '2026-10-07 12:00:00', '---
id:
-
- 4
username:
- ''''
- dave
email:
-
- dave@example.com
first_name:
-
- Dave
last_name:
-
- Deleted
encrypted_password:
- ''''
- cfb4ea3605835afdfe1f15c9f50807a4c9889a3773f13184691237b967be1144a0653e9f3086448709a0cd5552ca21f6010f6c9953d4ac6d1236827c5d40cbf6
password_salt:
- ''''
- t7J1wy9wrkFyXD5xM5sX
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2026-10-07 12:00:00.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-10-07 12:00:00.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2026-10-07 12:00:00.000000000 Z
confirmed_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: 2026-10-07 12:00:00.000000000 Z
  zone: *2
  time: 2026-10-07 12:00:00.000000000 Z
', NULL, NULL, NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (5, 'Campaign', 1, 'create', '1', NULL, '2026-10-07 12:00:00', '---
id:
-
- 1
user_id:
-
- 1
assigned_to:
-
- 2
name:
- ''''
- Autumn Launch
status:
-
- started
budget:
-
- !ruby/object:BigDecimal 18:0.250005e5
target_leads:
-
- 120
target_conversion:
-
- 12.5
target_revenue:
-
- !ruby/object:BigDecimal 9:0.25e6
revenue:
-
- !ruby/object:BigDecimal 18:0.125025e4
starts_on:
-
- 2026-09-01
ends_on:
-
- 2026-12-31
objectives:
-
- |-
  Line one
  Line two
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2026-10-07 12:00:00.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-10-07 12:00:00.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2026-10-07 12:00:00.000000000 Z
background_info:
-
- Campaign background
', NULL, NULL, NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (6, 'Campaign', 2, 'create', '1', NULL, '2026-10-07 12:00:00', '---
id:
-
- 2
user_id:
-
- 2
name:
- ''''
- Retired Campaign
access:
- Public
- Private
status:
-
- completed
deleted_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: 2026-09-27 12:00:00.000000000 Z
  zone: &1 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-09-27 12:00:00.000000000 Z
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &2 2026-10-07 12:00:00.000000000 Z
  zone: *1
  time: 2026-10-07 12:00:00.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *2
  zone: *1
  time: 2026-10-07 12:00:00.000000000 Z
', NULL, NULL, NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (7, 'Account', 1, 'create', '1', NULL, '2026-10-07 12:00:00', '---
id:
-
- 1
user_id:
-
- 1
assigned_to:
-
- 2
name:
- ''''
- Acme Corp
website:
-
- https://acme.example
toll_free_phone:
-
- 1-800-555-0199
phone:
-
- "+1 555 0199"
fax:
-
- "+1 555 0198"
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2026-10-07 12:00:00.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-10-07 12:00:00.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2026-10-07 12:00:00.000000000 Z
email:
-
- info@acme.example
background_info:
-
- |-
  Key account.
  Second line with ünïcödé.
rating:
- 0
- 4
category:
-
- customer
wikidata_id:
-
- Q42
latitude:
-
- !ruby/object:BigDecimal 18:0.37774929e2
longitude:
-
- !ruby/object:BigDecimal 18:-0.122419418e3
blog:
-
- https://acme.example/blog
linkedin:
-
- company/acme
facebook:
-
- acme
twitter:
-
- acme
bluesky:
-
- acme.bsky.social
instagram:
-
- acme
mastodon:
-
- "@acme@example.social"
', NULL, NULL, NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (8, 'Account', 2, 'create', '1', NULL, '2026-10-07 12:00:00', '---
id:
-
- 2
user_id:
-
- 2
name:
- ''''
- Globex
access:
- Public
- Private
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2026-10-07 12:00:00.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-10-07 12:00:00.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2026-10-07 12:00:00.000000000 Z
', NULL, NULL, NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (9, 'Account', 3, 'create', '1', NULL, '2026-10-07 12:00:00', '---
id:
-
- 3
user_id:
-
- 1
name:
- ''''
- Ünïcødé & Sons
access:
- Public
- Shared
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2026-10-07 12:00:00.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-10-07 12:00:00.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2026-10-07 12:00:00.000000000 Z
rating:
- 0
- 2
category:
-
- partner
', NULL, NULL, NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (10, 'Account', 4, 'create', '1', NULL, '2026-10-07 12:00:00', '---
id:
-
- 4
user_id:
-
- 1
name:
- ''''
- Initech
deleted_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: 2026-10-02 12:00:00.000000000 Z
  zone: &1 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-10-02 12:00:00.000000000 Z
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &2 2026-10-07 12:00:00.000000000 Z
  zone: *1
  time: 2026-10-07 12:00:00.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *2
  zone: *1
  time: 2026-10-07 12:00:00.000000000 Z
rating:
- 0
- 1
', NULL, NULL, NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (11, 'Lead', 1, 'create', '1', NULL, '2026-10-07 12:00:00', '---
id:
-
- 1
user_id:
-
- 1
campaign_id:
-
- 1
assigned_to:
-
- 2
first_name:
- ''''
- Lena
last_name:
- ''''
- Lead
title:
-
- CTO
company:
-
- Leadify
source:
-
- web
status:
-
- contacted
referred_by:
-
- Bob
email:
-
- lena@leadify.example
alt_email:
-
- lena.alt@leadify.example
phone:
-
- "+49 30 1234"
mobile:
-
- "+49 170 1234"
blog:
-
- https://leadify.example
linkedin:
-
- in/lena
facebook:
-
- lena
twitter:
-
- lena
rating:
- 0
- 3
do_not_call:
- false
- true
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2026-10-07 12:00:00.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-10-07 12:00:00.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2026-10-07 12:00:00.000000000 Z
background_info:
-
- Met at conference
zoom:
-
- lena-zoom
teams:
-
- lena-teams
signal:
-
- "+491701234"
instagram:
-
- lena
mastodon:
-
- "@lena@example.social"
bluesky:
-
- lena.bsky.social
', NULL, NULL, NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (12, 'Lead', 2, 'create', '1', NULL, '2026-10-07 12:00:00', '---
id:
-
- 2
user_id:
-
- 2
campaign_id:
-
- 1
first_name:
- ''''
- Carl
last_name:
- ''''
- Converted
status:
-
- converted
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2026-10-07 12:00:00.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-10-07 12:00:00.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2026-10-07 12:00:00.000000000 Z
', NULL, NULL, NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (13, 'Lead', 3, 'create', '1', NULL, '2026-10-07 12:00:00', '---
id:
-
- 3
user_id:
-
- 2
first_name:
- ''''
- Gone
last_name:
- ''''
- Lead
status:
-
- rejected
deleted_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: 2026-10-06 12:00:00.000000000 Z
  zone: &1 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-10-06 12:00:00.000000000 Z
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &2 2026-10-07 12:00:00.000000000 Z
  zone: *1
  time: 2026-10-07 12:00:00.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *2
  zone: *1
  time: 2026-10-07 12:00:00.000000000 Z
', NULL, NULL, NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (14, 'Contact', 1, 'create', '1', NULL, '2026-10-07 12:00:00', '---
id:
-
- 1
user_id:
-
- 1
assigned_to:
-
- 2
first_name:
- ''''
- Carla
last_name:
- ''''
- Chief
title:
-
- CEO
department:
-
- Executive
source:
-
- referral
email:
-
- carla@acme.example
alt_email:
-
- carla.alt@acme.example
phone:
-
- "+1 555 0110"
mobile:
-
- "+1 555 0111"
fax:
-
- "+1 555 0112"
blog:
-
- https://carla.example
linkedin:
-
- in/carla
facebook:
-
- carla
twitter:
-
- carla
born_on:
-
- 1975-02-28
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2026-10-07 12:00:00.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-10-07 12:00:00.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2026-10-07 12:00:00.000000000 Z
background_info:
-
- Decision maker
zoom:
-
- carla-zoom
teams:
-
- carla-teams
signal:
-
- "+15550111"
instagram:
-
- carla
mastodon:
-
- "@carla@example.social"
bluesky:
-
- carla.bsky.social
', NULL, NULL, NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (15, 'Contact', 2, 'create', '1', NULL, '2026-10-07 12:00:00', '---
id:
-
- 2
user_id:
-
- 2
lead_id:
-
- 2
reports_to:
-
- 1
first_name:
- ''''
- Carl
last_name:
- ''''
- Converted
access:
- Public
- Private
do_not_call:
- false
- true
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2026-10-07 12:00:00.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-10-07 12:00:00.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2026-10-07 12:00:00.000000000 Z
', NULL, NULL, NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (16, 'Contact', 3, 'create', '1', NULL, '2026-10-07 12:00:00', '---
id:
-
- 3
user_id:
-
- 2
first_name:
- ''''
- Former
last_name:
- ''''
- Contact
deleted_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: 2026-10-05 12:00:00.000000000 Z
  zone: &1 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-10-05 12:00:00.000000000 Z
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &2 2026-10-07 12:00:00.000000000 Z
  zone: *1
  time: 2026-10-07 12:00:00.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *2
  zone: *1
  time: 2026-10-07 12:00:00.000000000 Z
', NULL, NULL, NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (17, 'AccountContact', 1, 'create', '1', NULL, '2026-10-07 12:00:00', '---
account_id:
-
- 1
', 1, 'Contact', NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (18, 'AccountContact', 2, 'create', '1', NULL, '2026-10-07 12:00:00', '---
account_id:
-
- 2
', 2, 'Contact', NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (19, 'AccountContact', 3, 'create', '1', NULL, '2026-10-07 12:00:00', '---
account_id:
-
- 2
deleted_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: 2026-09-17 12:00:00.000000000 Z
  zone: !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-09-17 12:00:00.000000000 Z
', 1, 'Contact', NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (20, 'Opportunity', 1, 'create', '1', NULL, '2026-10-07 12:00:00', '---
id:
-
- 1
user_id:
-
- 1
campaign_id:
-
- 1
assigned_to:
-
- 2
name:
- ''''
- Acme renewal
source:
-
- campaign
stage:
-
- proposal
probability:
-
- 60
amount:
-
- !ruby/object:BigDecimal 18:0.123456789e7
discount:
-
- !ruby/object:BigDecimal 18:0.10001e4
closes_on:
-
- 2026-11-30
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2026-10-07 12:00:00.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-10-07 12:00:00.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2026-10-07 12:00:00.000000000 Z
background_info:
-
- Renewal
', NULL, NULL, NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (21, 'Opportunity', 2, 'create', '1', NULL, '2026-10-07 12:00:00', '---
id:
-
- 2
user_id:
-
- 2
name:
- ''''
- Globex pilot
access:
- Public
- Shared
stage:
-
- prospecting
probability:
-
- 10
amount:
-
- !ruby/object:BigDecimal 9:0.5e3
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2026-10-07 12:00:00.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-10-07 12:00:00.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2026-10-07 12:00:00.000000000 Z
', NULL, NULL, NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (22, 'Opportunity', 3, 'create', '1', NULL, '2026-10-07 12:00:00', '---
id:
-
- 3
user_id:
-
- 2
name:
- ''''
- Lost deal
stage:
-
- lost
deleted_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: 2026-10-04 12:00:00.000000000 Z
  zone: &1 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-10-04 12:00:00.000000000 Z
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &2 2026-10-07 12:00:00.000000000 Z
  zone: *1
  time: 2026-10-07 12:00:00.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *2
  zone: *1
  time: 2026-10-07 12:00:00.000000000 Z
', NULL, NULL, NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (23, 'AccountOpportunity', 1, 'create', '1', NULL, '2026-10-07 12:00:00', '---
id:
-
- 1
account_id:
-
- 1
opportunity_id:
-
- 1
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2026-10-07 12:00:00.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-10-07 12:00:00.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2026-10-07 12:00:00.000000000 Z
', NULL, NULL, NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (24, 'AccountOpportunity', 2, 'create', '1', NULL, '2026-10-07 12:00:00', '---
id:
-
- 2
account_id:
-
- 2
opportunity_id:
-
- 2
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2026-10-07 12:00:00.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-10-07 12:00:00.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2026-10-07 12:00:00.000000000 Z
', NULL, NULL, NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (25, 'AccountOpportunity', 3, 'create', '1', NULL, '2026-10-07 12:00:00', '---
id:
-
- 3
account_id:
-
- 1
opportunity_id:
-
- 2
deleted_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: 2026-10-03 12:00:00.000000000 Z
  zone: &1 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-10-03 12:00:00.000000000 Z
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &2 2026-10-07 12:00:00.000000000 Z
  zone: *1
  time: 2026-10-07 12:00:00.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *2
  zone: *1
  time: 2026-10-07 12:00:00.000000000 Z
', NULL, NULL, NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (26, 'Task', 1, 'create', '1', NULL, '2026-10-07 12:00:00', '---
id:
-
- 1
user_id:
-
- 1
assigned_to:
-
- 2
name:
- ''''
- Call Acme
asset_type:
-
- Account
asset_id:
-
- 1
priority:
-
- high
category:
-
- call
bucket:
-
- due_tomorrow
due_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: 2026-10-08 00:00:00.000000000 Z
  zone: &1 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-10-08 00:00:00.000000000 Z
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &2 2026-10-07 12:00:00.000000000 Z
  zone: *1
  time: 2026-10-07 12:00:00.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *2
  zone: *1
  time: 2026-10-07 12:00:00.000000000 Z
background_info:
-
- Discuss renewal
', 1, 'Account', NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (27, 'Task', 2, 'create', '1', NULL, '2026-10-07 12:00:00', '---
id:
-
- 2
user_id:
-
- 2
name:
- ''''
- Email Carla
asset_type:
-
- Contact
asset_id:
-
- 1
category:
-
- email
bucket:
-
- due_this_week
due_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: 2026-10-11 23:59:59.999999999 Z
  zone: &1 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-10-11 23:59:59.999999999 Z
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &2 2026-10-07 12:00:00.000000000 Z
  zone: *1
  time: 2026-10-07 12:00:00.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *2
  zone: *1
  time: 2026-10-07 12:00:00.000000000 Z
', 1, 'Contact', NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (28, 'Task', 3, 'create', '1', NULL, '2026-10-07 12:00:00', '---
id:
-
- 3
user_id:
-
- 1
name:
- ''''
- Standalone task
bucket:
-
- due_asap
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2026-10-07 12:00:00.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-10-07 12:00:00.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2026-10-07 12:00:00.000000000 Z
', NULL, NULL, NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (29, 'Task', 4, 'create', '1', NULL, '2026-10-07 12:00:00', '---
id:
-
- 4
user_id:
-
- 1
completed_by:
-
- 1
name:
- ''''
- Done task
asset_type:
-
- Opportunity
asset_id:
-
- 1
bucket:
-
- due_asap
completed_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: 2026-10-06 12:00:00.000000000 Z
  zone: &1 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-10-06 12:00:00.000000000 Z
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &2 2026-10-07 12:00:00.000000000 Z
  zone: *1
  time: 2026-10-07 12:00:00.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *2
  zone: *1
  time: 2026-10-07 12:00:00.000000000 Z
', 1, 'Opportunity', NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (30, 'Task', 5, 'create', '1', NULL, '2026-10-07 12:00:00', '---
id:
-
- 5
user_id:
-
- 2
name:
- ''''
- Deleted task
bucket:
-
- due_asap
deleted_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: 2026-10-07 11:00:00.000000000 Z
  zone: &1 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-10-07 11:00:00.000000000 Z
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &2 2026-10-07 12:00:00.000000000 Z
  zone: *1
  time: 2026-10-07 12:00:00.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *2
  zone: *1
  time: 2026-10-07 12:00:00.000000000 Z
', NULL, NULL, NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (31, 'Comment', 1, 'create', '1', NULL, '2026-10-07 12:00:00', '---
id:
-
- 1
user_id:
-
- 1
commentable_type:
-
- Account
commentable_id:
-
- 1
private:
-
- false
title:
- ''''
- Review
comment:
-
- Quarterly review scheduled with @bob.
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2026-10-07 12:00:00.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-10-07 12:00:00.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2026-10-07 12:00:00.000000000 Z
', 1, 'Account', NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (32, 'Comment', 2, 'create', '1', NULL, '2026-10-07 12:00:00', '---
id:
-
- 2
user_id:
-
- 2
commentable_type:
-
- Contact
commentable_id:
-
- 1
private:
-
- true
comment:
-
- Prefers morning calls.
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2026-10-07 12:00:00.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-10-07 12:00:00.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2026-10-07 12:00:00.000000000 Z
', 1, 'Contact', NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (33, 'Comment', 3, 'create', '1', NULL, '2026-10-07 12:00:00', '---
id:
-
- 3
user_id:
-
- 2
commentable_type:
-
- Task
commentable_id:
-
- 1
comment:
-
- On it.
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2026-10-07 12:00:00.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-10-07 12:00:00.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2026-10-07 12:00:00.000000000 Z
', 1, 'Task', NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (34, 'Email', 1, 'create', '1', NULL, '2026-10-07 12:00:00', '---
id:
-
- 1
imap_message_id:
-
- "<msg-1@example.com>"
user_id:
-
- 1
mediator_type:
-
- Account
mediator_id:
-
- 1
sent_from:
-
- alice@example.com
sent_to:
-
- info@acme.example
cc:
-
- bob@example.com
bcc:
-
- archive@example.com
subject:
-
- Renewal terms
body:
-
- |
  Hi,

  Please find the terms attached.
header:
-
- |-
  X-Mailer: Fixture
  X-Priority: 1
sent_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: 2026-10-07 10:00:00.000000000 Z
  zone: &1 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-10-07 10:00:00.000000000 Z
received_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: 2026-10-07 11:00:00.000000000 Z
  zone: *1
  time: 2026-10-07 11:00:00.000000000 Z
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &2 2026-10-07 12:00:00.000000000 Z
  zone: *1
  time: 2026-10-07 12:00:00.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *2
  zone: *1
  time: 2026-10-07 12:00:00.000000000 Z
', 1, 'Account', NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (35, 'Email', 2, 'create', '1', NULL, '2026-10-07 12:00:00', '---
id:
-
- 2
imap_message_id:
-
- "<msg-2@example.com>"
user_id:
-
- 2
mediator_type:
-
- Contact
mediator_id:
-
- 1
sent_from:
-
- bob@example.com
sent_to:
-
- carla@acme.example
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2026-10-07 12:00:00.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-10-07 12:00:00.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2026-10-07 12:00:00.000000000 Z
', 1, 'Contact', NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (36, 'Email', 3, 'create', '1', NULL, '2026-10-07 12:00:00', '---
id:
-
- 3
imap_message_id:
-
- "<msg-3@example.com>"
sent_from:
-
- nobody@example.com
sent_to:
-
- x@example.com
deleted_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: 2026-10-06 12:00:00.000000000 Z
  zone: &1 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-10-06 12:00:00.000000000 Z
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &2 2026-10-07 12:00:00.000000000 Z
  zone: *1
  time: 2026-10-07 12:00:00.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *2
  zone: *1
  time: 2026-10-07 12:00:00.000000000 Z
', NULL, NULL, NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (37, 'Address', 1, 'create', '1', NULL, '2026-10-07 12:00:00', '---
id:
-
- 1
street1:
-
- 1 Market St
street2:
-
- Suite 100
city:
-
- San Francisco
state:
-
- CA
zipcode:
-
- ''94105''
country:
-
- US
address_type:
-
- Business
addressable_type:
-
- Account
addressable_id:
-
- 1
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2026-10-07 12:00:00.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-10-07 12:00:00.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2026-10-07 12:00:00.000000000 Z
', 1, 'Account', NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (38, 'Address', 2, 'create', '1', NULL, '2026-10-07 12:00:00', '---
id:
-
- 2
full_address:
-
- Postfach 1, 10115 Berlin, DE
address_type:
-
- Billing
addressable_type:
-
- Contact
addressable_id:
-
- 1
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2026-10-07 12:00:00.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-10-07 12:00:00.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2026-10-07 12:00:00.000000000 Z
', 1, 'Contact', NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (39, 'Address', 3, 'create', '1', NULL, '2026-10-07 12:00:00', '---
id:
-
- 3
city:
-
- Hamburg
country:
-
- DE
address_type:
-
- Shipping
addressable_type:
-
- Lead
addressable_id:
-
- 1
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2026-10-07 12:00:00.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-10-07 12:00:00.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2026-10-07 12:00:00.000000000 Z
', 1, 'Lead', NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (40, 'Address', 4, 'create', '1', NULL, '2026-10-07 12:00:00', '---
id:
-
- 4
city:
-
- Old
address_type:
-
- Shipping
addressable_type:
-
- Account
addressable_id:
-
- 1
created_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: &1 2026-10-07 12:00:00.000000000 Z
  zone: &2 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-10-07 12:00:00.000000000 Z
updated_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: *1
  zone: *2
  time: 2026-10-07 12:00:00.000000000 Z
deleted_at:
-
- !ruby/object:ActiveSupport::TimeWithZone
  utc: 2026-09-28 12:00:00.000000000 Z
  zone: *2
  time: 2026-09-28 12:00:00.000000000 Z
', 1, 'Account', NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (41, 'Account', 1, 'update', '1', '---
id: 1
user_id: 1
assigned_to: 2
name: Acme Corp
access: Public
website: https://acme.example
toll_free_phone: 1-800-555-0199
phone: "+1 555 0199"
fax: "+1 555 0198"
deleted_at:
created_at: !ruby/object:ActiveSupport::TimeWithZone
  utc: 2026-10-07 12:00:00.000000000 Z
  zone: &1 !ruby/object:ActiveSupport::TimeZone
    name: Etc/UTC
  time: 2026-10-07 12:00:00.000000000 Z
updated_at: !ruby/object:ActiveSupport::TimeWithZone
  utc: 2026-10-07 12:00:00.000000000 Z
  zone: *1
  time: 2026-10-07 12:00:00.000000000 Z
email: info@acme.example
background_info: |-
  Key account.
  Second line with ünïcödé.
rating: 4
category: customer
subscribed_users: |
  ---
  - 1
  - 2
  - 2
  - 1
contacts_count: 1
opportunities_count: 2
wikidata_id: Q42
latitude: !ruby/object:BigDecimal 18:0.37774929e2
longitude: !ruby/object:BigDecimal 18:-0.122419418e3
blog: https://acme.example/blog
linkedin: company/acme
facebook: acme
twitter: acme
bluesky: acme.bsky.social
instagram: acme
mastodon: "@acme@example.social"
tag_list:
', '2026-10-07 12:00:00', '---
phone:
- "+1 555 0199"
- "+1 555 0200"
rating:
- 4
- 5
', NULL, NULL, NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (42, 'Account', 1, 'view', '2', NULL, '2026-10-07 12:00:00', NULL, 1, 'Account', NULL);
INSERT INTO public.versions (id, item_type, item_id, event, whodunnit, object, created_at, object_changes, related_id, related_type, transaction_id) VALUES (43, 'Task', 1, 'view', '1', NULL, '2026-10-07 12:00:00', NULL, NULL, NULL, NULL);


--
-- Name: account_contacts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.account_contacts_id_seq', 3, true);


--
-- Name: account_opportunities_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.account_opportunities_id_seq', 3, true);


--
-- Name: accounts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.accounts_id_seq', 4, true);


--
-- Name: action_text_rich_texts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.action_text_rich_texts_id_seq', 1, false);


--
-- Name: activities_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.activities_id_seq', 2, true);


--
-- Name: addresses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.addresses_id_seq', 4, true);


--
-- Name: avatars_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.avatars_id_seq', 2, true);


--
-- Name: campaigns_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.campaigns_id_seq', 2, true);


--
-- Name: comments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.comments_id_seq', 3, true);


--
-- Name: contact_opportunities_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.contact_opportunities_id_seq', 4, true);


--
-- Name: contacts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.contacts_id_seq', 3, true);


--
-- Name: emails_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.emails_id_seq', 3, true);


--
-- Name: field_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.field_groups_id_seq', 2, true);


--
-- Name: fields_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.fields_id_seq', 2, true);


--
-- Name: groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.groups_id_seq', 2, true);


--
-- Name: leads_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.leads_id_seq', 3, true);


--
-- Name: lists_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.lists_id_seq', 2, true);


--
-- Name: opportunities_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.opportunities_id_seq', 3, true);


--
-- Name: permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.permissions_id_seq', 3, true);


--
-- Name: preferences_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.preferences_id_seq', 4, true);


--
-- Name: research_tools_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.research_tools_id_seq', 2, true);


--
-- Name: sessions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.sessions_id_seq', 1, false);


--
-- Name: settings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.settings_id_seq', 4, true);


--
-- Name: taggings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.taggings_id_seq', 4, true);


--
-- Name: tags_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.tags_id_seq', 3, true);


--
-- Name: tasks_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.tasks_id_seq', 5, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_id_seq', 4, true);


--
-- Name: versions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.versions_id_seq', 43, true);


--
-- PostgreSQL database dump complete
--


