package com.fatfreecrm.security;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.fatfreecrm.support.RailsUserFixtures;
import com.fatfreecrm.support.RailsUserFixtures.LegacyUser;
import java.util.List;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

/**
 * Byte-for-byte comparison against hashes generated by the Rails app. If this
 * class fails, existing users cannot log in to the Spring service and the
 * fallback is a forced password reset campaign (see the Phase 1 exit criteria).
 */
class AuthlogicSha512PasswordEncoderTest {

    private static final int CONFIGURED_STRETCHES = 20;

    private final AuthlogicSha512PasswordEncoder encoder =
        new AuthlogicSha512PasswordEncoder(CONFIGURED_STRETCHES);

    static List<LegacyUser> railsUsers() {
        return RailsUserFixtures.users();
    }

    @Test
    void fixtureWasGeneratedByTheEncryptorWeReproduce() {
        assertThat(RailsUserFixtures.encryptor()).isEqualTo("authlogic_sha512");
        assertThat(RailsUserFixtures.declaredStretches()).isEqualTo(encoder.getStretches());
        assertThat(RailsUserFixtures.pepper()).isNull();
        assertThat(RailsUserFixtures.deviseVersion()).isNotBlank();
        assertThat(RailsUserFixtures.deviseEncryptableVersion()).isEqualTo("0.2.0");
    }

    @Test
    void fixtureContainsRailsGenerationProvenance() {
        assertThat(RailsUserFixtures.generatedAt()).isNotBlank();
        assertThat(RailsUserFixtures.railsEnv()).isEqualTo("development");
        assertThat(RailsUserFixtures.source()).isEqualTo("persisted User rows created with User.create!");
        assertThat(RailsUserFixtures.transaction()).isEqualTo("rolled_back_after_reading_rows");
    }

    @ParameterizedTest
    @MethodSource("railsUsers")
    void reproducesRailsDigestExactly(LegacyUser user) {
        assertThat(encoder.digest(user.password(), user.passwordSalt()))
            .isEqualTo(user.encryptedPassword());
    }

    @ParameterizedTest
    @MethodSource("railsUsers")
    void matchesRailsHash(LegacyUser user) {
        assertThat(encoder.matches(user.password(), user.encryptedPassword(), user.passwordSalt())).isTrue();
    }

    @ParameterizedTest
    @MethodSource("railsUsers")
    void rejectsWrongPasswordAndWrongSalt(LegacyUser user) {
        assertThat(encoder.matches(user.password() + "x", user.encryptedPassword(), user.passwordSalt())).isFalse();
        assertThat(encoder.matches(user.password(), user.encryptedPassword(), "not-the-salt")).isFalse();
    }

    @Test
    void digestIsSensitiveToStretchCount() {
        LegacyUser user = RailsUserFixtures.users().getFirst();
        String withOneFewerStretch = new AuthlogicSha512PasswordEncoder(encoder.getStretches() - 1)
            .digest(user.password(), user.passwordSalt());
        assertThat(withOneFewerStretch).isNotEqualTo(user.encryptedPassword());
    }

    @Test
    void producesHexSha512Output() {
        assertThat(encoder.digest("whatever", "salt")).hasSize(128).matches("[0-9a-f]{128}");
    }

    @Test
    void treatsBlankStoredHashAsNoMatch() {
        assertThat(encoder.matches("whatever", "", "salt")).isFalse();
        assertThat(encoder.matches("whatever", null, "salt")).isFalse();
    }

    @Test
    void rejectsNonsensicalStretchCounts() {
        assertThatThrownBy(() -> new AuthlogicSha512PasswordEncoder(0))
            .isInstanceOf(IllegalArgumentException.class);
    }

    @Test
    void saltBoundViewDelegatesToTheSameDigest() {
        LegacyUser user = RailsUserFixtures.users().getFirst();
        assertThat(encoder.forSalt(user.passwordSalt()).matches(user.password(), user.encryptedPassword())).isTrue();
        assertThat(encoder.forSalt(user.passwordSalt()).encode(user.password())).isEqualTo(user.encryptedPassword());
    }
}
