package com.fatfreecrm.domain;

import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;

/**
 * Surrogate-key base for every Rails table: {@code id bigserial} generated by PostgreSQL so Rails and Spring
 * can insert concurrently without coordinating sequence state.
 */
@MappedSuperclass
public abstract class BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    public Long getId() {
        return id;
    }

    public boolean isNew() {
        return id == null;
    }
}
