package com.fatfreecrm.spike.customfields;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Test;

/**
 * The fixtures were generated by real Ruby Psych (see generate_yaml_fixtures.rb),
 * so decoding them proves parity with Rails' serialize(type: Array) format.
 */
class CheckBoxesYamlCodecTest {

    private static final ObjectMapper MAPPER = new ObjectMapper();

    @Test
    void decodesEveryPsychFixture() throws Exception {
        CheckBoxesYamlCodec codec = new CheckBoxesYamlCodec();
        try (InputStream in = CheckBoxesYamlCodecTest.class
            .getResourceAsStream("/spike/customfields/check_boxes_yaml_fixtures.json")) {
            JsonNode root = MAPPER.readTree(in);
            for (JsonNode node : root) {
                List<String> expected = new ArrayList<>();
                node.get("values").forEach(v -> expected.add(v.asText()));
                assertThat(codec.decode(node.get("yaml").asText()))
                    .as("decode of %s", expected)
                    .isEqualTo(expected);
            }
        }
    }

    @Test
    void encodeDecodeRoundTrip() throws Exception {
        CheckBoxesYamlCodec codec = new CheckBoxesYamlCodec();
        try (InputStream in = CheckBoxesYamlCodecTest.class
            .getResourceAsStream("/spike/customfields/check_boxes_yaml_fixtures.json")) {
            JsonNode root = MAPPER.readTree(in);
            for (JsonNode node : root) {
                List<String> values = new ArrayList<>();
                node.get("values").forEach(v -> values.add(v.asText()));
                // encode -> decode must give the same array (output is double-quoted,
                // which Psych loads back identically)
                assertThat(codec.decode(codec.encode(values))).isEqualTo(values);
            }
        }
    }

    @Test
    void edgeCases() {
        CheckBoxesYamlCodec codec = new CheckBoxesYamlCodec();
        assertThat(codec.decode(null)).isEmpty();
        assertThat(codec.decode("")).isEmpty();
        assertThat(codec.decode("   ")).isEmpty();
        // non-string scalars are stringified
        assertThat(codec.decode("---\n- 1\n- true\n")).containsExactly("1", "true");
        // non-sequence YAML is rejected
        assertThatThrownBy(() -> codec.decode("---\nfoo: bar\n"))
            .isInstanceOf(IllegalArgumentException.class);
        assertThat(codec.encode(List.of())).isEqualTo("--- []\n");
    }
}
