package com.fatfreecrm.service.validation;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.io.InputStream;
import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Component;

/**
 * ActiveModel error-message catalog for the write API: loads
 * {@code validation/activemodel_en_US.json} (generated by {@code rake
 * ffcrm:migration:activemodel_messages}) and reproduces {@code Errors#generate_message}'s lookup
 * chain and {@code full_message} semantics — the leading {@code ^} suppresses the attribute name
 * and is stripped, otherwise the message is prefixed via {@code errors.format}
 * ("%{attribute} %{message}").
 */
@Component
public class ActiveModelMessages {

    static final String RESOURCE = "/validation/activemodel_en_US.json";

    private final JsonNode catalog;

    public ActiveModelMessages() {
        this(defaultCatalog());
    }

    ActiveModelMessages(JsonNode catalog) {
        this.catalog = catalog;
    }

    private static JsonNode defaultCatalog() {
        try (InputStream input = ActiveModelMessages.class.getResourceAsStream(RESOURCE)) {
            if (input == null) {
                throw new IllegalStateException("Missing " + RESOURCE + " on the classpath");
            }
            return new ObjectMapper().readTree(input);
        } catch (IOException exception) {
            throw new IllegalStateException("Could not load " + RESOURCE, exception);
        }
    }

    /**
     * ActiveModel {@code generate_message}: resolves the first hit of
     * {@code activerecord.errors.models.<model>.attributes.<attr>.<key>} →
     * {@code activerecord.errors.models.<model>.<key>} →
     * {@code activerecord.errors.messages.<key>} → {@code errors.attributes.<attr>.<key>} →
     * {@code errors.messages.<key>}, interpolating {@code %{attribute}/%{value}/%{count}}.
     * Defaults to {@code "is invalid"} ({@code :invalid}) when nothing matches.
     */
    public String generateMessage(
        String model,
        String attribute,
        String key,
        Map<String, ?> variables
    ) {
        String template = first(
            List.of(
                "activerecord.errors.models." + model + ".attributes." + attribute + "." + key,
                "activerecord.errors.models." + model + "." + key,
                "activerecord.errors.messages." + key,
                "errors.attributes." + attribute + "." + key,
                "errors.messages." + key
            ));
        if (template == null) {
            template = "is invalid";
        }
        return interpolate(template, model, attribute, variables);
    }

    /**
     * ActiveModel {@code full_message}: caret messages suppress the attribute; everything else is
     * prefixed via {@code errors.format}.
     */
    public String fullMessage(String model, String attribute, String message) {
        if (message.startsWith("^")) {
            return message.substring(1);
        }
        String format = first(List.of("errors.format"));
        if (format == null) {
            format = "%{attribute} %{message}";
        }
        return format
            .replace("%{attribute}", humanAttributeName(model, attribute))
            .replace("%{message}", message);
    }

    /** Rails {@code human_attribute_name}: {@code activerecord.attributes.<model>.<attr>} lookup. */
    public String humanAttributeName(String model, String attribute) {
        String name = first(List.of("activerecord.attributes." + model + "." + attribute));
        if (name != null) {
            return name;
        }
        String humanized = attribute.replace('_', ' ');
        return humanized.substring(0, 1).toUpperCase(java.util.Locale.ROOT) + humanized.substring(1);
    }

    private String interpolate(
        String template,
        String model,
        String attribute,
        Map<String, ?> variables
    ) {
        String result = template
            .replace("%{attribute}", humanAttributeName(model, attribute))
            .replace("%{model}", model);
        if (variables != null) {
            for (Map.Entry<String, ?> entry : variables.entrySet()) {
                result = result.replace("%{" + entry.getKey() + "}",
                    entry.getValue() == null ? "" : entry.getValue().toString());
            }
        }
        return result;
    }

    private String first(List<String> paths) {
        for (String path : paths) {
            JsonNode node = catalog.at("/" + path.replace(".", "/"));
            if (node.isTextual()) {
                return node.asText();
            }
        }
        return null;
    }
}
