package com.fatfreecrm;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.junit.jupiter.api.Test;

/**
 * Pure file-level checks that the committed V1 migration is exactly the Rails fixture produced by
 * {@code spring/scripts/generate-baseline.sh}, so the two artifacts cannot drift apart silently.
 */
class BaselineArtifactsConsistencyTest {

    private static final Path MIGRATION = Path.of("src/main/resources/db/migration/V1__baseline_rails_schema.sql");
    private static final Path FIXTURE = Path.of("src/test/resources/db/rails/rails_schema.sql");
    private static final Path SCHEMA_RB = Path.of("../db/schema.rb");
    private static final String SEARCH_PATH_LINE = "SELECT pg_catalog.set_config('search_path', '', false);";
    private static final Pattern SCHEMA_VERSION =
        Pattern.compile("ActiveRecord::Schema\\[[^\\]]+\\]\\.define\\(version: ([0-9_]+)\\)");

    @Test
    void migrationBodyIsTheRailsFixtureWithoutTheSearchPathReset() throws IOException {
        List<String> migration = Files.readAllLines(MIGRATION);
        List<String> fixture = Files.readAllLines(FIXTURE);

        List<String> migrationBody = migration.stream().dropWhile(line -> line.startsWith("-- ")).toList();
        List<String> fixtureWithoutSearchPath = fixture.stream()
            .filter(line -> !line.equals(SEARCH_PATH_LINE))
            .toList();

        assertThat(fixture).contains(SEARCH_PATH_LINE);
        assertThat(migration).doesNotContain(SEARCH_PATH_LINE);
        assertThat(migrationBody).isEqualTo(fixtureWithoutSearchPath);
    }

    @Test
    void migrationHeaderNamesTheCurrentRailsSchemaVersion() throws IOException {
        Matcher matcher = SCHEMA_VERSION.matcher(Files.readString(SCHEMA_RB));
        assertThat(matcher.find()).as("db/schema.rb declares a schema version").isTrue();
        String version = matcher.group(1);

        String header = Files.readAllLines(MIGRATION).get(0);
        assertThat(header).isEqualTo(
            "-- Generated by spring/scripts/generate-baseline.sh from db/schema.rb version " + version + "."
        );
        assertThat(Files.readString(MIGRATION))
            .contains("('" + version.replace("_", "") + "')");
    }

    @Test
    void artifactsAreFreeOfPgDumpDirectivesFlywayCannotParse() throws IOException {
        for (Path artifact : List.of(MIGRATION, FIXTURE)) {
            String content = Files.readString(artifact);
            assertThat(content).as("%s", artifact)
                .doesNotContain("\\restrict")
                .doesNotContain("\\unrestrict")
                .doesNotContain("-- Dumped from database version")
                .doesNotContain("-- Dumped by pg_dump version")
                .doesNotContain("OWNER TO")
                .doesNotContain("GRANT ");
        }
    }

    @Test
    void migrationSeedsSchemaMigrationsAndKeepsRailsMetadataTables() throws IOException {
        String migration = Files.readString(MIGRATION);
        assertThat(migration)
            .contains("CREATE TABLE public.schema_migrations (")
            .contains("CREATE TABLE public.ar_internal_metadata (")
            .containsPattern(
                "INSERT INTO public\\.schema_migrations \\(version\\) VALUES \\('\\d{14}'\\)(,\\('\\d{14}'\\))+;"
            );
        assertThat(migration.lines().filter(line -> line.startsWith("INSERT INTO")).count())
            .as("only the schema_migrations seed inserts data")
            .isEqualTo(1);
    }
}
