# frozen_string_literal: true

require "yaml"

# AB-273 (settings-i18n): converts each config/locales/fat_free_crm.*.yml file into a
# Spring-side ICU4J .properties file under spring/src/main/resources/i18n/.
#
# Rules (mirrors docs/adr/ab-273-peripherals.md):
# * The locale is the file's top-level key, not the filename (fat_free_crm.de-DE.yml -> de).
# * String keys are flattened with '.'; non-String keys (e.g. Psych booleans from `yes:`/`no:`)
#   and nil leaves are skipped — both are unreachable via Rails dotted lookup.
# * Plural hashes (non-empty keys subset of zero/one/two/few/many/other) become ICU
#   `{count, plural, ...}` choice formats; `zero` maps to the exact `=0` form. A plural hash
#   without `other` raises. Inside plural branches `%{name}` interpolations become `{name}`
#   and `%{count}` becomes `{count, number, ::group-off}` (Rails interpolates `count.to_s`
#   with no grouping); `%%`/`%<x>` raise there because ICU has no syntax for them.
# * Plain string leaves are emitted VERBATIM in Rails `%{name}`/`%%`/`%<x>s` form — Rails
#   only interpolates when arguments are passed and returns the raw string otherwise, so the
#   Spring side reimplements that substitution instead of round-tripping through ICU.
# * Literal text INSIDE plural branches uses ICU ApostropheMode.DOUBLE_OPTIONAL escaping:
#   `'` -> `''`, literal `{`/`}` -> `'{'`/`'}'`, and literal `#` -> `'#'`.
# * Output is UTF-8 with Java-Properties escaping applied to keys and values, sorted keys,
#   and a generated-by header. Deterministic.
module FatFreeCRM
  module Migration
    module I18nProperties
      PLURAL_KEYS = %w[zero one two few many other].freeze
      HEADER = "# GENERATED by rake ffcrm:migration:i18n_properties from config/locales/%s; do not edit."
      INTERPOLATION = /%\{([^}]+)\}/

      module_function

      def generate(locales_dir:, output_dir:)
        skipped = []
        files = Dir.glob(File.join(locales_dir, "fat_free_crm.*.yml"))
        raise "no locale files found in #{locales_dir}" if files.empty?

        FileUtils.mkdir_p(output_dir)
        files.each do |path|
          tree = YAML.load_file(path)
          locale = tree.keys.first
          raise "#{path}: expected a single top-level locale key" unless tree.size == 1 && locale.is_a?(String)

          messages = {}
          flatten(tree[locale], "", File.basename(path), messages, skipped)
          tag = locale.tr("-", "_")
          output = File.join(output_dir, "messages_#{tag}.properties")
          File.write(output, render(messages, File.basename(path)), encoding: "UTF-8")
        end
        skipped
      end

      def render(messages, source_file)
        lines = [format(HEADER, source_file)]
        messages.keys.sort.each do |key|
          lines << "#{escape_key(key)}=#{escape_value(messages[key])}"
        end
        lines.join("\n") + "\n"
      end

      def flatten(node, prefix, source, messages, skipped)
        node.each do |key, value|
          unless key.is_a?(String)
            skipped << "#{source}: skipped non-string key #{key.inspect} at #{prefix.empty? ? '(root)' : prefix}"
            next
          end

          dotted = prefix.empty? ? key : "#{prefix}.#{key}"
          case value
          when nil
            skipped << "#{source}: skipped nil leaf #{dotted}"
          when Hash
            if plural_hash?(value)
              messages[dotted] = icu_plural(value, dotted)
            else
              flatten(value, dotted, source, messages, skipped)
            end
          when String
            messages[dotted] = value
          else
            raise "#{source}: unsupported leaf #{value.class} at #{dotted}"
          end
        end
      end

      def plural_hash?(hash)
        !hash.empty? && (hash.keys - PLURAL_KEYS).empty?
      end

      def icu_plural(branches, context)
        raise "plural hash at #{context} has no 'other' branch" unless branches.key?("other")

        parts = PLURAL_KEYS.filter_map do |name|
          text = branches[name]
          next if text.nil?

          label = name == "zero" ? "=0" : name
          "#{label}{#{icu_message(text, in_plural: true, context: "#{context}.#{name}")}}"
        end
        "{count, plural, #{parts.join(' ')}}"
      end

      # Converts a single Rails translation string to an ICU message pattern.
      def icu_message(text, in_plural:, context:)
        raise "#{context}: unsupported %% at #{text.inspect}" if text.include?("%%")
        raise "#{context}: unsupported %<x> at #{text.inspect}" if text.match?(/%<[a-zA-Z_]+>/)

        text.split(INTERPOLATION).each_with_index.map do |segment, index|
          if index.odd?
            name = segment
            name == "count" ? "{count, number, ::group-off}" : "{#{name}}"
          else
            escape_literal(segment, in_plural: in_plural)
          end
        end.join
      end

      def escape_literal(segment, in_plural:)
        escaped = segment.gsub("'", "''").gsub("{", "'{'").gsub("}", "'}'")
        escaped = escaped.gsub("#", "'#'") if in_plural
        escaped
      end

      # Java .properties escaping: backslash, newline, CR, tab, leading space, and (in keys)
      # the separator characters space/colon/equals/hash/bang.
      def escape_key(key)
        escape_common(key).gsub(/[ :=#!]/) { |char| "\\#{char}" }
      end

      def escape_value(value)
        escape_common(value).sub(/\A /, '\\ ')
      end

      def escape_common(text)
        text.gsub("\\", "\\\\").gsub("\n", '\\n').gsub("\r", '\\r').gsub("\t", '\\t')
      end
    end
  end
end
