# frozen_string_literal: true

require "find"
require "yaml"

# AB-273 (settings-i18n): census of every `Setting` call site and every `cf_` occurrence in
# app/, lib/, config/, classified by ordered rules into ported / partial / not_ported / n/a
# against the Spring migration. Generates docs/migration/settings-cf-coverage.md; CHECK=1
# fails when a call site matches no rule or when the row multiset drifts from the committed
# markdown (line-number-only drift warns but does not fail).
module FatFreeCRM
  module Migration
    class SettingsCfCoverage
      SCAN_DIRS = %w[app lib config].freeze
      SETTING_RE = /\bSetting(?:\.(\w+[?!=]?)|\[([^\]]+)\])/
      # The tool's own files are the only exclusions.
      EXCLUDED = %w[
        lib/fat_free_crm/migration/settings_cf_coverage.rb
        lib/tasks/ffcrm/settings_cf_coverage.rake
        spec/lib/fat_free_crm/migration/settings_cf_coverage_spec.rb
      ].freeze
      STATUSES = %w[ported partial not_ported n/a unclassified].freeze
      GENERATE_CMD = "bundle exec rake ffcrm:migration:settings_cf_coverage"
      CHECK_CMD = "#{GENERATE_CMD} CHECK=1"

      Row = Struct.new(:kind, :file, :line, :member, :snippet, :status, :detail, keyword_init: true)

      def initialize(root:, rules_path:, markdown_path:)
        @root = root
        @rules = YAML.load_file(rules_path)
        @markdown_path = markdown_path
      end

      def scan
        rows = []
        SCAN_DIRS.each do |dir|
          base = File.join(@root, dir)
          next unless File.directory?(base)

          Find.find(base) do |path|
            next unless File.file?(path)
            next unless text_file?(path)

            relative = path.delete_prefix("#{@root}/")
            next if EXCLUDED.include?(relative)

            File.readlines(path, encoding: "UTF-8").each_with_index do |text, index|
              text.scan(SETTING_RE) do |member, bracketed|
                rows << Row.new(
                  kind: "setting", file: relative, line: index + 1,
                  member: member ? "#{member}#{call_args(text, Regexp.last_match.end(0))}" : "[#{bracketed}]",
                  snippet: text.strip
                )
              end
              rows << Row.new(kind: "cf", file: relative, line: index + 1, member: nil, snippet: text.strip) if text.include?("cf_")
            end
          end
        end
        rows.each { |row| classify(row) }
        rows.sort_by! { |row| [row.kind, row.file, row.line] }
        rows
      end

      def classify(row)
        rule = @rules.find do |candidate|
          candidate.fetch("kind") == row.kind &&
            path_match?(candidate.fetch("path"), row.file) &&
            (candidate["member"].nil? || row.member.to_s.match?(Regexp.new(candidate["member"])))
        end
        if rule
          row.status = rule.fetch("status")
          row.detail = rule["component"] || rule["reason"] || ""
        else
          row.status = "unclassified"
          row.detail = "matches no rule in settings-cf-coverage.rules.yml"
        end
        row
      end

      def markdown(rows)
        lines = [
          "# Setting / `cf_` call-site coverage (AB-273 settings-i18n)",
          "",
          "> GENERATED by `#{GENERATE_CMD}` — do not edit. Regenerate with the same command;",
          "> verify freshness with `#{CHECK_CMD}`.",
          "",
          "## Summary",
          "",
          "| kind | status | count |",
          "| --- | --- | --- |"
        ]
        rows.group_by { |row| [row.kind, row.status] }.sort.each do |(kind, status), group|
          lines << "| #{kind} | #{status} | #{group.size} |"
        end
        lines += [
          "",
          "## Call sites",
          "",
          "| kind | file:line | member/key | snippet | status | Spring component or reason |",
          "| --- | --- | --- | --- | --- | --- |"
        ]
        rows.each do |row|
          lines << "| #{row.kind} | #{row.file}:#{row.line} | #{row.member} | `#{escape_cell(row.snippet)}` | " \
                   "#{row.status} | #{escape_cell(row.detail.to_s)} |"
        end
        lines.join("\n") + "\n"
      end

      # Returns {unclassified: [rows], added: [sig], removed: [sig], line_drift: [sig]}.
      def check(rows)
        committed = parse_markdown(File.exist?(@markdown_path) ? File.read(@markdown_path) : "")
        current = rows.index_by do |row|
          [row.kind, row.file, row.member.to_s, normalize(row.snippet)]
        end
        added = (current.keys - committed.keys).sort
        removed = (committed.keys - current.keys).sort
        line_drift = current.filter_map do |sig, row|
          committed[sig] if committed.key?(sig) && committed[sig] != row.line
        end
        { unclassified: rows.select { |row| row.status == "unclassified" }, added: added, removed: removed, line_drift: line_drift }
      end

      private

      # `dir/**` in fnmatch only matches direct children; treat it as recursive like
      # minimatch/File.fnmatch '**/*' semantics.
      def path_match?(pattern, file)
        File.fnmatch?(pattern, file, File::FNM_PATHNAME | File::FNM_EXTGLOB) ||
          (pattern.end_with?("/**") &&
            File.fnmatch?("#{pattern}/*", file, File::FNM_PATHNAME | File::FNM_EXTGLOB))
      end

      # Captures the argument list immediately following a member call so that
      # `Setting.unroll(:task_bucket)` records member `unroll(:task_bucket)` — needed because
      # the same `unroll` member maps to different Spring components per setting key.
      def call_args(text, position)
        return "" unless text[position] == "("

        depth = 0
        text[position..].each_char.with_index do |char, offset|
          depth += 1 if char == "("
          depth -= 1 if char == ")"
          return text[position, offset + 1] if depth.zero?
        end
        ""
      end

      def text_file?(path)
        File.open(path, "rb") { |file| file.read(4096).to_s.exclude?("\0") }
      rescue SystemCallError
        false
      end

      def normalize(snippet)
        snippet.gsub(/\s+/, " ").strip
      end

      def escape_cell(text)
        text.gsub("|", "\\|")
      end

      # Parses the committed markdown table back into {signature => line}.
      def parse_markdown(text)
        text.each_line.with_object({}) do |line, rows|
          cells = line.strip.split(/(?<!\\)\|/).map { |cell| cell.strip.gsub("\\|", "|") }
          location = cells[2]&.match(/\A(.+):(\d+)\z/)
          next unless cells.size >= 7 && %w[setting cf].include?(cells[1]) && location

          snippet = cells[4].sub(/\A`/, "").sub(/`\z/, "")
          rows[[cells[1], location[1], cells[3].to_s, normalize(snippet)]] = location[2].to_i
        end
      end
    end
  end
end
